import {useEffect,useState,type FormEvent} from "react";
import {useMunicipalityContext} from "../context/MunicipalityContext";
import {ensureRadarAccessToken} from "../data/radarAuth";
type Member={user_id:string;email:string;member_role:string};type Team={seat_limit:number;members:Member[]};
export function CampaignTeamSettings(){const {campaign_id,user_role}=useMunicipalityContext();const [team,setTeam]=useState<Team|null>(null);const [editing,setEditing]=useState<Member|null>(null);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const allowed=user_role==="municipal_admin";
 async function request(action:string,input:Record<string,unknown>={}){const token=await ensureRadarAccessToken();const response=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/radar-campaign-team`,{method:"POST",headers:{apikey:import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({action,campaign_id,input})});const result=await response.json();if(!response.ok||result.error)throw new Error(result.error||"No se pudo gestionar el equipo");return result.data;}
 useEffect(()=>{if(allowed)void request("list").then(setTeam).catch(e=>setMessage(e.message));},[campaign_id,allowed]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const values=Object.fromEntries(new FormData(e.currentTarget));try{await request(editing?(values.member_role==="remove"?"remove":"assign"):"invite",{...values,...(editing?{user_id:editing.user_id}:{})});setTeam(await request("list"));setOpen(false);setMessage("Acceso actualizado.");}catch(error){setMessage(error instanceof Error?error.message:"No se pudo guardar");}finally{setBusy(false);}}
 if(!allowed)return null;
 return <section className="config-overview" id="equipo-accesos"><article><small>ADMINISTRACIÓN DE CAMPAÑA</small><h2>Equipo y accesos</h2><p>{team?`${team.members.length} de ${team.seat_limit} cuentas utilizadas · tu cuenta incluida`:"Cargando equipo…"}</p><p>Los accesos temporales de fiscales no consumen este cupo.</p>{team?.members.map(m=><div key={m.user_id} style={{display:"flex",justifyContent:"space-between",gap:16,padding:"14px 0",borderBottom:"1px solid #ddd"}}><span><b>{m.email}</b><br/>{m.member_role==="campaign_admin"?"Administrador":m.member_role==="campaign_editor"?"Editor":"Consulta"}</span>{m.member_role!=="campaign_admin"&&<button onClick={()=>{setEditing(m);setOpen(true);}}>Editar acceso</button>}</div>)}<button type="button" disabled={!team||team.members.length>=team.seat_limit} onClick={()=>{setEditing(null);setOpen(true);}}>+ Agregar usuario</button>{message&&<p role="status">{message}</p>}{open&&<form onSubmit={save} style={{display:"grid",gap:14,marginTop:20}}><h3>{editing?editing.email:"Nuevo usuario"}</h3>{!editing&&<><label>Nombre<input name="display_name" required/></label><label>Correo<input name="email" type="email" required/></label></>}<label>Permisos<select name="member_role" defaultValue={editing?.member_role??"campaign_editor"}><option value="campaign_editor">Editor · agrega y modifica información</option><option value="campaign_viewer">Consulta · solo lectura</option>{editing&&<option value="remove">Retirar acceso · conservar información</option>}</select></label><p>Para cambiar al administrador principal o ampliar el cupo, contacta a RADAR.</p><button disabled={busy}>{busy?"Guardando…":"Confirmar"}</button><button type="button" disabled={busy} onClick={()=>setOpen(false)}>Cancelar</button></form>}</article></section>;
}
