import type { DemoActivity, DemoGeoFeature } from "../types/radar";

const colors: Record<DemoGeoFeature["feature_type"], string> = { boundary: "transparent", microrregion: "#6e3d8a", community: "#123f46", voting_center: "#dc5f3b", school: "#d5a529", health: "#2f927f", project: "#596674" };
const labels: Record<DemoGeoFeature["feature_type"], string> = { boundary: "Límite sintético", microrregion: "Microrregiones", community: "Comunidades", voting_center: "Centros de votación", school: "Escuelas", health: "Salud", project: "Proyectos" };

function polygonPoints(feature: DemoGeoFeature | undefined) { const ring = feature?.geometry_json?.coordinates?.[0]; return Array.isArray(ring) ? ring.map(([x, y]) => `${x},${y}`).join(" ") : "8,8 92,12 96,58 72,92 20,88 6,44"; }

export function OperationalMap({ features, activities }: { features: DemoGeoFeature[]; activities: DemoActivity[] }) {
  const boundary = features.find((feature) => feature.feature_type === "boundary"); const points = features.filter((feature) => feature.feature_type !== "boundary"); const locatedActivities = activities.filter((activity) => activity.latitude !== null && activity.longitude !== null);
  const counts = Object.keys(labels).flatMap((type) => type === "boundary" ? [] : [{ type: type as DemoGeoFeature["feature_type"], count: points.filter((feature) => feature.feature_type === type).length }]);
  return <div className="demo-map-canvas operational-map-canvas" data-demo-features={features.length}><svg viewBox="0 0 100 100" role="img" aria-label="Mapa operativo de Valle Nexo con 27 elementos geográficos"><defs><pattern id="operational-grid" width="10" height="10" patternUnits="userSpaceOnUse"><path d="M 10 0 L 0 0 0 10" fill="none" stroke="currentColor" strokeWidth=".12" /></pattern></defs><rect width="100" height="100" className="demo-map-grid" /><polygon className="demo-boundary" points={polygonPoints(boundary)} />{points.map((feature) => <g key={feature.id} className={`demo-map-point demo-map-point--${feature.feature_type}`}>{feature.feature_type === "microrregion" ? <circle cx={feature.x} cy={feature.y} r="7" fill={colors[feature.feature_type]} opacity=".12" /> : null}<circle cx={feature.x} cy={feature.y} r={feature.feature_type === "community" ? 1.45 : 1.9} fill={colors[feature.feature_type]} />{feature.feature_type === "community" || feature.feature_type === "voting_center" ? <text x={feature.x + 2.2} y={feature.y - 1.7}>{feature.feature_name}</text> : null}</g>)}{locatedActivities.map((activity) => <g key={activity.id} className="demo-map-activity"><circle cx={activity.longitude ?? 50} cy={activity.latitude ?? 50} r="2.2" /><text x={(activity.longitude ?? 50) + 2.5} y={(activity.latitude ?? 50) - 2}>{activity.title}</text></g>)}</svg><aside className="demo-map-legend"><small>MAPA OPERATIVO · NO CORRESPONDE A UN MUNICIPIO REAL</small>{counts.map(({ type, count }) => <span key={type}><i style={{ background: colors[type] }} /><b>{labels[type]}</b><em>{count}</em></span>)}<span><i className="activity" /><b>Actividades georreferenciadas</b><em>{locatedActivities.length}</em></span></aside></div>;
}
