import { useEffect, useMemo, useState, type ChangeEvent, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { Link, useParams } from "react-router-dom";
import { useMunicipalityContext } from "../context/MunicipalityContext";
import { getInstalledRadarElectoralLayers } from "../data/radarRuntimeCache";
import { adaptAuthorizedElectoralTerritoryLayers } from "../data/v70ElectoralAdapter";

function SectionBanner({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: ReactNode }) {
  return <section className="section-banner"><div className="section-banner-copy"><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></div>{actions ? <div className="section-banner-actions">{actions}</div> : null}</section>;
}

function InternalViews({ views, label }: { views: Array<{ key: string; label: string; content: ReactNode }>; label: string }) {
  const [active, setActive] = useState(views[0]?.key ?? "");
  const selected = views.find((view) => view.key === active) ?? views[0];
  if (!selected) return null;
  return <section className="internal-view-shell"><span className="internal-view-mobile-hint" aria-hidden="true">Desliza para ver más opciones →</span><nav className="internal-view-tabs" aria-label={label}>{views.map((view) => <button key={view.key} className={view.key === selected.key ? "active" : ""} onClick={() => setActive(view.key)} type="button"><span>{view.label}</span></button>)}</nav><div className="internal-view-content" data-view={selected.key}>{selected.content}</div></section>;
}

function StrategyClient() {
  const days = Math.max(0, Math.ceil((new Date("2027-06-27T00:00:00-06:00").getTime() - Date.now()) / 86_400_000));
  const [scenario, setScenario] = useState({ conservador: "", base: "", optimista: "" });
  const areas = [
    ["01", "Plan de campaña", "Diagnóstico, objetivos y decisiones vigentes", "inteligencia"],
    ["02", "Comunicación", "Banco oficial de fotografías, logos y piezas", "recursos"],
    ["03", "Control Financiero", "Ingresos, egresos, comprobantes y presupuesto", "recursos"],
    ["04", "Legal", "Expedientes de candidatos y documentos del partido", "recursos"],
  ] as const;
  return <><SectionBanner eyebrow="DIRECCIÓN DE CAMPAÑA" title="Estrategia" description="Objetivos, decisiones y ejecución conectada de la campaña municipal" /><section className="campaign-command-center campaign-command-clean"><div className="campaign-election-row"><aside className="election-countdown compact" aria-label="Cuenta regresiva electoral"><div><strong>{days} días</strong><span>para las elecciones</span></div><small>Fecha preliminar: 27 de junio de 2027 · pendiente de convocatoria oficial del TSE</small></aside><aside className="campaign-legal-deadline" aria-label="Próximo hito del calendario electoral"><small>PRÓXIMO HITO TSE · PRELIMINAR</small><div><b>Convocatoria a elecciones</b><span>22 ENE 2027</span></div><Link to="../dia-d">Ver calendario →</Link></aside></div><section className="strategy-goals" aria-labelledby="strategy-goals-title"><header><div><small>RADAR + CAMPAÑA</small><h2 id="strategy-goals-title">Metas y Escenarios</h2></div><p>Los datos superiores son referencias calculadas por RADAR. Los escenarios son objetivos internos definidos por la campaña, no predicciones.</p></header><div className="strategy-goals-radar"><article><small>Padrón estimado 2027</small><b>41,563</b></article><article><small>Participación de referencia</small><b>67.8%</b></article><article className="magic"><small>Número mágico</small><b>9,000</b><i>Estimación RADAR</i></article></div><div className="strategy-scenarios"><label><span>Escenario conservador</span><input inputMode="numeric" value={scenario.conservador} onChange={(event) => setScenario({ ...scenario, conservador: event.target.value.replace(/[^0-9]/g, "") })} placeholder="Votos objetivo" /><small>Definido por la campaña</small></label><label><span>Escenario base</span><input inputMode="numeric" value={scenario.base} onChange={(event) => setScenario({ ...scenario, base: event.target.value.replace(/[^0-9]/g, "") })} placeholder="Votos objetivo" /><small>Definido por la campaña</small></label><label><span>Escenario optimista</span><input inputMode="numeric" value={scenario.optimista} onChange={(event) => setScenario({ ...scenario, optimista: event.target.value.replace(/[^0-9]/g, "") })} placeholder="Votos objetivo" /><small>Definido por la campaña</small></label></div><footer><span>Base: elecciones municipales 2011–2023, crecimiento del padrón y participación observada.</span><button type="button">Guardar escenarios</button></footer></section><section className="campaign-state-clean" aria-labelledby="campaign-state-title"><header><small>ÁREAS DE TRABAJO</small><h2 id="campaign-state-title">Estado de la Campaña</h2></header><div>{areas.map(([mark, name, detail, href]) => <Link to={`../${href}`} key={name}><i>{mark}</i><span><b>{name}</b><small>{detail}</small></span><em>Entrar →</em></Link>)}</div></section></section></>;
}

const demoElectors = [
  ["QA-0001", "Persona de prueba 01", "BARRIO PEÑATE", "34", "SIN CONTACTO", "Sin teléfono"],
  ["QA-0002", "Persona de prueba 02", "PUEBLO SAN JOSE", "41", "CONTACTADO", "5555 0002"],
  ["QA-0003", "Persona de prueba 03", "PARCELAMIENTO LOS ANGELES", "29", "LIDER", "5555 0003"],
  ["QA-0004", "Persona de prueba 04", "SANTA ISABEL", "52", "SIN CONTACTO", "Sin teléfono"],
  ["QA-0005", "Persona de prueba 05", "ARIZONA", "38", "CONTACTADO", "5555 0005"],
] as const;

function ElectorDirectoryPreview() {
  const [query, setQuery] = useState("");
  const visible = demoElectors.filter((item) => !query.trim() || item[1].toLowerCase().includes(query.toLowerCase()) || item[2].toLowerCase().includes(query.toLowerCase()));
  return <><section className="elector-kpis" aria-label="Resumen del Directorio"><span><b>38,934</b><small>Registros 2023</small></span><span><b>0</b><small>Contactos</small></span><span><b>0</b><small>Líderes</small></span><span><b>205</b><small>Comunidades</small></span></section><section className="elector-filters"><label className="wide"><span>Nombre</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Nombre o palabras aproximadas" /></label><label><span>DPI</span><input inputMode="numeric" placeholder="DPI completo" /></label><label><span>Comunidad</span><select defaultValue=""><option value="">Todas</option><option>BARRIO PEÑATE</option><option>PUEBLO SAN JOSE</option><option>PARCELAMIENTO LOS ANGELES</option></select></label><label><span>Edad estimada</span><select defaultValue=""><option value="">Todas</option><option>18–29</option><option>30–44</option><option>45–59</option><option>60 o más</option></select></label><label><span>Estado</span><select defaultValue=""><option value="">Todos</option><option>SIN CONTACTO</option><option>CONTACTADO</option><option>LIDER</option></select></label><label><span>Afiliado al partido</span><select defaultValue=""><option value="">—</option><option>Sí</option><option>No</option></select></label><label><span>Responsable</span><select defaultValue=""><option value="">Todos</option></select></label><label><span>Rol</span><input placeholder="Ej. fiscal o liderazgo" /></label><button type="button">Limpiar</button><button type="button" className="primary">+ Agregar contacto</button></section><section className="elector-results"><header><div><small>RESULTADOS · QA PRIVADO</small><h2>38,934 personas</h2></div><label>Por página<select defaultValue="25"><option>25</option><option>50</option></select></label></header><div className="elector-table" role="table"><div className="elector-row head" role="row"><span>Persona</span><span>Comunidad</span><span>Edad estimada</span><span>Estado</span><span>Contacto</span><span /></div>{visible.map((item) => <button className="elector-row" role="row" key={item[0]}><span className="elector-person"><i aria-hidden="true">QA</i><span><b>{item[1]}</b><small>•••• ••••• ••••</small></span></span><span>{item[2]}</span><span>{item[3]}</span><span><i className={`elector-status status-${item[4].toLowerCase().replace(" ", "_")}`}>{item[4]}</i></span><span>{item[5]}</span><span>→</span></button>)}</div><footer><button disabled>← Anterior</button><span>Página <b>1</b> de 1,558</span><button>Siguiente →</button></footer></section></>;
}

function DirectoryClient() {
  const [mode, setMode] = useState<"electors" | "team">("electors");
  return <><SectionBanner eyebrow="CRM" title="Directorio" description={mode === "electors" ? "Base electoral municipal y seguimiento" : "Base de datos / contactos por tipo"} actions={mode === "team" ? <><button className="secondary">↓ Descargar Excel</button><button>+ Agregar contacto</button></> : undefined} /><nav className="directory-universe-tabs" aria-label="Universos del Directorio"><button className={mode === "electors" ? "active" : ""} onClick={() => setMode("electors")}><b>Posibles votantes</b><span>Base precargada del municipio</span></button><button className={mode === "team" ? "active" : ""} onClick={() => setMode("team")}><b>Equipo y responsables</b><span>Operación interna de campaña</span></button></nav>{mode === "electors" ? <ElectorDirectoryPreview /> : <><section className="crm-controlbar"><label className="crm-search"><span>⌕</span><input placeholder="Buscar nombre, teléfono, comunidad o cargo" /></label><label><span>Tipo de contacto</span><select defaultValue="all"><option value="all">Todos</option><option>Candidato</option><option>Coordinador</option><option>Fiscal</option><option>Líder</option></select></label><button className="crm-bulk-carnets">↓ Carnets (12)</button><div className="crm-view-switch"><button className="active">Tarjetas</button><button>Lista</button></div></section><section className="crm-directory crm-directory-v2"><header><div><small>CAMPAIGN VAULT · PRIVADO</small><h2>12 contactos visibles</h2></div></header><div className="crm-card-grid">{Array.from({ length: 6 }, (_, index) => <article className="crm-contact-card" key={index}><header><span><i>NA</i><b>Nombre Apellido</b><small>{index === 0 ? "Candidato" : index < 3 ? "Coordinación" : "Fiscal"}</small></span><em>QA</em></header><div className="crm-contact-lines"><span><b>Teléfono principal</b><em>Pendiente</em></span><span><b>Comunidad</b><em>San José</em></span><span><b>Calidad</b><em>Completar</em></span></div><footer><div className="crm-card-actions"><Link to="../agenda">Crear actividad</Link><div className="crm-card-secondary"><button>Imprimir</button><button>Abrir</button></div></div></footer></article>)}</div></section></>}</>;
}

const milestones = [
  ["22 ENE 2027", "Convocatoria a elecciones"], ["23 ENE–28 MAR", "Postulación e inscripción de candidatos"], ["20 MAR 2027", "Cierre de inscripción de ciudadanos"], ["29 MAR 2027", "Inicio del período de campaña electoral"], ["24–30 ABR", "Publicación del padrón electoral"], ["28 ABR 2027", "Definición del número de JRV por municipio"], ["28 MAY 2027", "Publicidad del financiamiento"], ["25 JUN · 12:00", "Cierre de campaña, propaganda y encuestas"], ["27 JUN 2027", "Elecciones generales"],
] as const;

function AgendaClient() {
  const [view, setView] = useState<"calendar" | "list">("calendar");
  const now = new Date();
  return <><SectionBanner eyebrow="OPERACIÓN" title="Agenda" description="Actividades, compromisos, tareas y calendario electoral conectados a la campaña" actions={<button>+ Nuevo elemento</button>} /><section className="agenda-next"><article className="empty"><div><small>PRÓXIMA ACTIVIDAD EN LA AGENDA</small><h2>Sin actividades programadas</h2><p>El calendario está listo para recibir la operación territorial.</p></div><button>+ Crear actividad</button></article></section><section className="agenda-viewbar"><div><button className={view === "calendar" ? "active" : ""} onClick={() => setView("calendar")}>Calendario</button><button className={view === "list" ? "active" : ""} onClick={() => setView("list")}>Lista</button></div><Link to="../mapa">Ver actividades en el mapa →</Link></section><section className="agenda-workspace"><div className="agenda-calendar"><header><div><small>AGENDA COMPARTIDA</small><h2>{view === "calendar" ? now.toLocaleDateString("es-GT", { month: "long", year: "numeric" }) : "Próximas actividades"}</h2></div>{view === "calendar" ? <nav><button>←</button><button>Hoy</button><button>→</button></nav> : null}</header>{view === "calendar" ? <div className="month-grid"><div className="month-week">{["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"].map((day) => <span key={day}>{day}</span>)}</div><div className="month-days">{Array.from({ length: 35 }, (_, index) => index < 30 ? <article className={index + 1 === now.getDate() ? "today" : ""} key={index}><b>{index + 1}</b></article> : <span key={index} />)}</div></div> : <div className="agenda-empty"><b>No hay actividades futuras.</b><span>Agrega la primera actividad de campaña.</span><button>+ Nueva actividad</button></div>}</div><aside><small>CALENDARIO ELECTORAL</small><h2>Guatemala 2027</h2><p className="electoral-note">Fechas preliminares del TSE, sujetas al decreto oficial de convocatoria.</p><div className="electoral-date-list">{milestones.map(([date, title]) => <article className="electoral-date" key={title}><time>{date}</time><b>{title}</b><span>OPERACIÓN · PRELIMINAR</span></article>)}</div></aside></section></>;
}

function DayDClient() {
  const { municipality_code } = useMunicipalityContext();
  const layers = getInstalledRadarElectoralLayers(municipality_code) ?? [];
  const view = useMemo(() => { try { return layers.length ? adaptAuthorizedElectoralTerritoryLayers(layers) : null; } catch { return null; } }, [layers]);
  const centers = view?.centers ?? [];
  const totalJrv = centers.reduce((sum, center) => sum + center.jrv, 0);
  const command = <section className="day-d-command"><header><small>JORNADA ELECTORAL</small><h2>Centro de mando</h2></header><div className="day-d-summary"><button type="button"><small>Centros de votación</small><b>{centers.length || 13}</b><span>Abrir organización →</span></button><button type="button"><small>JRV de referencia</small><b>{totalJrv || 103}</b><span>Revisar cobertura →</span></button><button type="button"><small>Fiscales en CRM</small><b>0</b><span>Ver supervisión →</span></button><button type="button"><small>Incidencias abiertas</small><b>0</b><span>Abrir incidencias →</span></button></div></section>;
  const centerView = <section className="day-d-workspace"><header><div><small>COBERTURA TSE</small><h2>Centros de votación y JRV</h2><p>Organización territorial y asignación de responsables y fiscales.</p></div></header><div className="day-d-center-list">{(centers.length ? centers : Array.from({ length: 13 }, (_, index) => ({ id: String(index + 1).padStart(3, "0"), name: `Centro de votación ${index + 1}`, community: "San José", jrv: 8, voters: 2995, jrvRange: "—" }))).map((center) => <article key={center.id}><span><small>REFERENCIA RADAR · {center.id}</small><button>{center.name}</button><em>{center.community}</em></span><strong>0/{center.jrv} JRV con fiscal · {Number(center.voters ?? 0).toLocaleString("es-GT")} electores</strong><small>JRV {center.jrvRange}</small></article>)}</div></section>;
  const fiscales = <section className="day-d-workspace"><header><div><small>SUPERVISIÓN CASI EN TIEMPO REAL</small><h2>Fiscales</h2><p>Estados enviados desde el portal ligero. El alcance se deriva de la sesión fiscal, nunca de IDs escritos en el navegador.</p></div><a className="day-d-open-fiscal" href="#">Abrir portal fiscal público</a></header><div className="day-d-operations-strip"><span><small>JRV con fiscal</small><b>0/{totalJrv || 103}</b></span><span><small>Check-in completados</small><b>0</b></span><span><small>Necesitan apoyo</small><b>0</b></span><span><small>RTD ingresado</small><b>0</b></span></div><div className="day-d-fiscal-table extended"><div className="head"><span>Fiscal / asignación</span><span>Check-in</span><span>Transporte</span><span>Comida</span><span>Datos</span><span>Cierre</span><span>RTD</span><span>Acceso / sincronización</span></div><p>No hay fiscales asignados en esta campaña QA.</p></div></section>;
  const incidencias = <section className="day-d-workspace"><header><div><small>ALERTA, EVIDENCIA Y RESPUESTA</small><h2>Incidencias</h2><p>Registros normalizados con folio, archivos privados, acciones e historial. La evidencia del fiscal no se elimina.</p></div></header><div className="day-d-filters"><label><span>Estado</span><select defaultValue="ABIERTAS"><option>ABIERTAS</option><option>RESUELTAS</option><option>TODAS</option></select></label></div><div className="day-d-incident-list"><p>No hay incidencias con este filtro.</p></div></section>;
  const logistica = <section className="day-d-workspace day-d-logistics-workspace"><header><div><small>PREPARACIÓN Y RESPUESTA DÍA D</small><h2>Logística</h2><p>Rutas, transporte, alimentación, datos y kits coordinados desde una sola orden operativa.</p></div><nav className="day-d-logistics-links"><Link to="../recursos">Vehículos y recursos</Link><button>+ Nueva previsión</button></nav></header><div className="logistics-summary"><span><small>Rutas / traslados</small><b>0</b></span><span><small>Personas o porciones previstas</small><b>0</b></span><span><small>Recargas planificadas</small><b>0</b></span><span className="ready"><small>Pendientes o incidencias</small><b>0</b></span><span><small>Costo estimado</small><b>Q 0.00</b></span></div><div className="logistics-start-grid">{["Transporte electores", "Traslado fiscales", "Alimentación", "Datos móviles", "Kit electoral", "Equipo respaldo"].map((item) => <button key={item}><b>+</b><span>{item}</span><small>Preparar operación</small></button>)}</div></section>;
  const rtd = <section className="day-d-workspace"><header><div><small>RESULTADOS TRANSMITIDOS DESDE MESA</small><h2>RTD</h2><p>Folios, actas y control de recepción separados entre demostración y resultados reales.</p></div></header><div className="day-d-rtd-list"><p>No hay folios enviados todavía.</p></div></section>;
  return <><SectionBanner eyebrow="COORDINACIÓN" title="Día D" description="Centro de mando, fiscales, movilización, incidencias y reportes" /><InternalViews label="Centro de operaciones Día D" views={[{ key: "mando", label: "Centro de mando", content: command }, { key: "centros", label: "Centros de votación y JRV", content: centerView }, { key: "fiscales", label: "Fiscales", content: fiscales }, { key: "incidencias", label: "Incidencias", content: incidencias }, { key: "logistica", label: "Logística", content: logistica }, { key: "rtd", label: "RTD", content: rtd }]} /></>;
}

function ResourcesClient() {
  const materials = <section className="resources-workspace"><header><small>BIBLIOTECA</small><h2>Documentos precargados</h2></header><div className="preloaded-resource-grid">{[["Manuales", "Protocolos operativos y electorales validados."], ["Checklists", "Apertura, jornada, cierre y control de evidencias."], ["Plantillas", "Formatos reutilizables para campaña y Día D."], ["Tutoriales y Capacitación", "Guías en distintos formatos para campaña y utilización de RADAR."]].map(([title, detail]) => <article key={title}><i>▤</i><b>{title}</b><span>{detail}</span><button type="button">Abrir</button></article>)}</div></section>;
  const physical = <section className="resources-workspace"><header><small>BANCO DE RECURSOS</small><h2>Recursos físicos</h2><p>Vehículos, sedes, equipo audiovisual, materiales promocionales y otros activos.</p></header><section className="physical-bank"><div className="physical-resource-types">{["Vehículos", "Sedes", "Equipo audiovisual", "Material promocional", "Otros"].map((label) => <button type="button" key={label}><b>0</b><span>{label}</span><small><i>+</i> Agregar</small></button>)}</div><header className="physical-bank-bar"><div><small>BANCO DE RECURSOS</small><h2>Vehículos</h2></div><button>+ Agregar vehículos</button></header><div className="physical-bank-list"><div className="agenda-empty"><b>No hay vehículos registrados.</b><button>Agregar el primero</button></div></div></section></section>;
  const official = <section className="resources-workspace"><header><small>CONEXIÓN CON COMUNICACIÓN, AGENDA Y DIRECTORIO</small><h2>Archivos oficiales</h2><p>Fotografías del candidato, materiales aprobados, logotipo del partido y fotografías de actividades.</p></header><section className="communication-library"><header><nav><button className="active">Todo</button><button>Candidato</button><button>Partido</button><button>Actividades</button></nav><div><button className="secondary">+ Carpeta</button><button>+ Nueva carga</button></div></header><div className="communication-album"><div className="communication-empty"><b>Banco oficial listo para recibir piezas.</b><span>Carga fotografías, logotipos y materiales aprobados de campaña.</span><button>Nueva carga</button></div></div></section></section>;
  return <><SectionBanner eyebrow="INVENTARIO OPERATIVO" title="Recursos" description="Documentos, activos físicos y archivos oficiales de campaña" /><InternalViews label="Vistas internas de Recursos" views={[{ key: "materiales", label: "Materiales", content: materials }, { key: "fisicos", label: "Recursos físicos", content: physical }, { key: "oficiales", label: "Archivos oficiales", content: official }]} /></>;
}

const pulseRows = [["Planilla VALOR", "VALOR", 32], ["Planilla VAMOS", "VAMOS", 25], ["Planilla UNE", "UNE", 21], ["Planilla PPN", "PPN", 8], ["No sabe / no responde", "", 14]] as const;
function PulseClient() {
  const [election, setElection] = useState("Alcaldía");
  return <><SectionBanner eyebrow="MEDICIÓN Y TENDENCIAS" title="Pulso Electoral" description="Encuestas comparables, metodología visible y tendencias sin inventar certeza" /><main className="pulse-dashboard"><section className="pulse-disclaimer demo"><span><b>SIMULACIÓN VISUAL</b><small>Candidaturas y organizaciones 2023 con porcentajes simulados. No es una encuesta ni un resultado electoral.</small></span><nav><button className="active">Demostración 2023</button><button>Encuestas RADAR</button></nav></section><section className="pulse-election-tabs" aria-label="Tipo de elección">{["Alcaldía", "Presidencia", "Lista nacional", "Distrito"].map((label) => <button key={label} className={election === label ? "active" : ""} onClick={() => setElection(label)}>{label}</button>)}</section><section className="pulse-overview"><article><small>ÚLTIMA MEDICIÓN</small><b>jun 2023</b><span>San José / Puerto San José</span></article><article><small>MUESTRA</small><b>400</b></article><article><small>PRIMERA POSICIÓN</small><b>32.0%</b><span>{pulseRows[0][0]}</span></article><article><small>CAMBIO ÚLTIMA OLA</small><b>+1.0 pts</b><span>Comparación homogénea</span></article></section><section className="pulse-main-grid single"><article className="pulse-ranking"><header><div><small>INTENCIÓN DE VOTO · SAN JOSÉ / PUERTO SAN JOSÉ</small><h2>{election}</h2></div><strong>jun 2023</strong></header><div>{pulseRows.map((row, index) => <article key={row[0]}><span><i style={{ background: ["#09566C", "#5A2973", "#C47A5A", "#65736B", "#A7ACA5"][index] }} /><b>{row[0]}</b><small>{row[1] || "Sin organización"}</small></span><strong>{row[2].toFixed(1)}%</strong><div><i style={{ width: `${row[2]}%`, background: ["#09566C", "#5A2973", "#C47A5A", "#65736B", "#A7ACA5"][index] }} /></div></article>)}</div><footer>Valores simulados exclusivamente para validar la experiencia de Pulso Electoral.</footer></article></section><section className="pulse-trend"><header><small>EVOLUCIÓN COMPARABLE</small><h2>Intención de voto a lo largo del tiempo</h2></header><div className="pulse-trend-wrap"><svg className="pulse-trend-chart" viewBox="0 0 720 250" role="img" aria-label="Evolución simulada"><polyline points="45,125 360,112 702,100" style={{ stroke: "#09566C" }} /><polyline points="45,155 360,145 702,138" style={{ stroke: "#5A2973" }} /><circle cx="702" cy="100" r="5" style={{ fill: "#09566C" }} /><circle cx="702" cy="138" r="5" style={{ fill: "#5A2973" }} /><text className="pulse-axis-date" x="45" y="240">abr 2023</text><text className="pulse-axis-date" x="360" y="240">may 2023</text><text className="pulse-axis-date" x="660" y="240">jun 2023</text></svg><div className="pulse-trend-legend"><span><i style={{ background: "#09566C" }} /><b>Planilla VALOR</b></span><span><i style={{ background: "#5A2973" }} /><b>Planilla VAMOS</b></span></div></div></section></main></>;
}

function AiClient() {
  const [task, setTask] = useState("consulta");
  const [input, setInput] = useState("");
  const starters = ["¿Cuáles son las tres prioridades reales de la campaña esta semana y por qué?", "¿Qué información falta para tomar mejores decisiones en el municipio?", "Resume el estado de Agenda, responsables y compromisos abiertos.", "¿Qué comunidades grandes tienen menor cobertura operativa?", "Propón un plan de 7 días con responsables y resultados verificables."];
  return <><SectionBanner eyebrow="CAPA TRANSVERSAL" title="IA RADAR" description="Consultar, resumir y relacionar evidencia y operación sin duplicar datos" /><main className="radar-ai-page"><section className="ai-source-scope"><header><small>FUENTES CONECTADAS</small><h2>Una sola capa de consulta</h2><p>IA RADAR relaciona el contexto municipal y los resúmenes autorizados del Campaign Vault según los permisos del usuario.</p></header><div>{["Inteligencia Municipal", "Estrategia", "Directorio", "Agenda", "Mapa", "Día D", "Recursos", "Pulso Electoral"].map((item) => <span key={item}>{item}</span>)}</div><aside><b>Recomendación de IA ≠ decisión aprobada</b><span>Briefs, prioridades, resúmenes y borradores deben ser revisados por la campaña antes de convertirse en instrucciones o mensajes oficiales.</span></aside></section><section className="radar-ai-assistant"><header className="radar-ai-statusbar"><div><b>IA RADAR</b><span>Contexto autorizado · 0509</span></div><span>QA cliente</span></header><div className="radar-ai-workbench"><div className="radar-ai-starters"><small>PREGUNTAS PARA EMPEZAR</small>{starters.map((question) => <button type="button" key={question} onClick={() => setInput(question)}>{question}</button>)}</div><div className="radar-ai-toolbar"><label><span>Tarea</span><select value={task} onChange={(event) => setTask(event.target.value)}><option value="organizar">Ordenar y priorizar</option><option value="resumir">Resumen ejecutivo</option><option value="revisar">Mejorar un campo</option><option value="consulta">Análisis de campaña</option><option value="intervencion">Plan de acción</option></select></label><span><b>Fuente</b> RADAR autorizado</span></div><label className="radar-ai-input"><span>Consulta</span><textarea rows={7} value={input} onChange={(event) => setInput(event.target.value)} placeholder="Pregunta sobre la campaña, el municipio o la operación…" /></label><div className="radar-ai-actions"><button type="button">Limpiar</button><button type="button" className="primary">Consultar IA RADAR</button></div></div></section></main></>;
}

function ConfigurationClient() {
  const [photo, setPhoto] = useState("");
  const changePhoto = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => setPhoto(String(reader.result || "")); reader.readAsDataURL(file); };
  return <><SectionBanner eyebrow="CONTROL DEL PORTAL" title="Configuración" description="Identidad, acceso, privacidad, alertas y preferencias de la campaña" /><main className="configuration-center simplified"><section className="config-overview"><article><small>CAMPAÑA</small><b>Nombre Apellido</b><span>Organización política</span><Link to="../directorio">Administrar identidad desde el CRM →</Link></article><article><small>MUNICIPIO</small><b>Municipio 0509</b><span>San José · Escuintla</span><em>El alcance está protegido por la sesión.</em></article><article><small>VAULT</small><b>Privado por campaña</b><span>Auditoría y archivos protegidos</span><em>Las consultas sensibles quedan trazadas.</em></article></section><section className="config-essential-grid"><article><header><small>PERFIL</small><h2>Fotografía de usuario</h2></header><div className="config-user-photo">{photo ? <img src={photo} alt="Fotografía del usuario" /> : <i>CM</i>}<label><span>Cambiar fotografía</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={changePhoto} /></label></div><p>Se utiliza en el acceso personal y ayuda a distinguir cuentas.</p></article><article><header><small>ACCESO RÁPIDO</small><h2>Datos maestros</h2></header><nav><Link to="../directorio">Equipo y responsables</Link><Link to="../recursos">Banco de recursos</Link><Link to="../dia-d">Centros, fiscales y JRV</Link></nav><p>La identidad de campaña se actualiza desde las tarjetas CRM y los archivos oficiales.</p></article><article><header><small>SEGURIDAD</small><h2>Sesión</h2></header><p>Usa una cuenta individual. El municipio, la campaña y los permisos se validan en cada operación.</p><button type="button">Cerrar sesión</button></article></section></main></>;
}

function ClientModule({ section }: { section: string }) {
  if (section === "estrategia") return <StrategyClient />;
  if (section === "directorio") return <DirectoryClient />;
  if (section === "agenda") return <AgendaClient />;
  if (section === "dia-d") return <DayDClient />;
  if (section === "recursos") return <ResourcesClient />;
  if (section === "pulso") return <PulseClient />;
  if (section === "ia-radar") return <AiClient />;
  if (section === "configuracion") return <ConfigurationClient />;
  return null;
}

const clientSections = new Set(["estrategia", "directorio", "agenda", "dia-d", "recursos", "pulso", "ia-radar", "configuracion"]);

export function V70ClientModulesParityBridge() {
  const { section } = useParams();
  const { municipality_code } = useMunicipalityContext();
  const [host, setHost] = useState<HTMLElement | null>(null);

  useEffect(() => {
    if (municipality_code !== "0509" || !section || !clientSections.has(section)) return;
    const main = document.querySelector<HTMLElement>(".portal-main");
    const topbar = main?.querySelector<HTMLElement>(":scope > header.portal-topbar");
    if (!main || !topbar) return;
    const existing = main.querySelector<HTMLElement>("[data-v70-client-module-slot]");
    const slot = existing ?? document.createElement("div");
    slot.dataset.v70ClientModuleSlot = section;
    slot.style.display = "contents";
    if (!existing) topbar.insertAdjacentElement("afterend", slot);
    const previous = Array.from(main.children).filter((node): node is HTMLElement => node instanceof HTMLElement && node !== topbar && node !== slot).map((node) => ({ node, hidden: node.hidden }));
    previous.forEach(({ node }) => { node.hidden = true; });
    setHost(slot);
    return () => {
      previous.forEach(({ node, hidden }) => { node.hidden = hidden; });
      if (!existing) slot.remove();
      setHost(null);
    };
  }, [municipality_code, section]);

  return host && section ? createPortal(<ClientModule section={section} />, host) : null;
}
