import { useEffect, useMemo, useState } from "react";
import { Navigate, useParams } from "react-router-dom";
import { MunicipalityProvider } from "../context/MunicipalityContext";
import { resolveRadarConsumer } from "../data/radarConsumer";
import { V70DirectShell0509 } from "./V70DirectShell0509";

type PuterUser={username?:string};
type PuterResponse=string|{text?:string;message?:{content?:string|Array<{text?:string}>}};
type PuterApi={auth:{isSignedIn:()=>boolean;signIn:(options?:{attempt_temp_user_creation?:boolean})=>Promise<unknown>;signOut:()=>Promise<unknown>;getUser:()=>Promise<PuterUser>};ai:{chat:(messages:Array<{role:"system"|"user";content:string}>,options?:Record<string,unknown>)=>Promise<PuterResponse>}};
declare global{interface Window{puter?:PuterApi}}
const taskOptions=[{value:"organizar",label:"Ordenar y priorizar",short:true},{value:"resumir",label:"Resumen ejecutivo",short:true},{value:"revisar",label:"Mejorar un campo",short:true},{value:"consulta",label:"Análisis de campaña",short:false},{value:"intervencion",label:"Plan de acción",short:false}] as const;
type TaskValue=(typeof taskOptions)[number]["value"];
const starterQuestions=["¿Cuáles son las tres prioridades reales de la campaña esta semana y por qué?","¿Qué información falta para tomar mejores decisiones en el municipio?","Resume el estado de Agenda, responsables y compromisos abiertos.","¿Qué comunidades grandes tienen menor cobertura operativa?","Propón un plan de 7 días con responsables y resultados verificables.","Revisa nuestro mensaje central frente a los problemas municipales documentados.","¿Qué riesgos legales, financieros u operativos requieren atención inmediata?","Prepara un brief para la próxima actividad territorial.","¿Qué debe verificar el centro de mando antes del Día D?","Compara los últimos pulsos electorales sin mezclar universos ni fechas."];
function extractText(response:PuterResponse){if(typeof response==="string")return response; if(response.text)return response.text; const content=response.message?.content; if(typeof content==="string")return content; if(Array.isArray(content))return content.map((item)=>item.text||"").join("\n"); return "";}

function RadarAssistant(){const [scriptReady,setScriptReady]=useState(Boolean(window.puter)); const [puterUser,setPuterUser]=useState<PuterUser|null>(null); const [connecting,setConnecting]=useState(false); const [task,setTask]=useState<TaskValue>("organizar"); const [input,setInput]=useState(""); const [result,setResult]=useState(""); const [status,setStatus]=useState(""); const [working,setWorking]=useState(false); const [copied,setCopied]=useState(false); const selectedTask=useMemo(()=>taskOptions.find((option)=>option.value===task)??taskOptions[0],[task]);
useEffect(()=>{if(window.puter){setScriptReady(true); if(window.puter.auth.isSignedIn())void window.puter.auth.getUser().then(setPuterUser).catch(()=>setPuterUser(null)); return;} const existing=document.getElementById("puter-js") as HTMLScriptElement|null; const script=existing??document.createElement("script"); if(!existing){script.id="puter-js";script.src="https://js.puter.com/v2/";script.async=true;document.head.appendChild(script);} const ready=()=>{setScriptReady(true); if(window.puter?.auth.isSignedIn())void window.puter.auth.getUser().then(setPuterUser).catch(()=>setPuterUser(null));}; script.addEventListener("load",ready); return()=>script.removeEventListener("load",ready);},[]);
async function connect(){if(!window.puter){setStatus("La conexión todavía está cargando. Intenta nuevamente en unos segundos.");return;} setConnecting(true);setStatus("");try{if(!window.puter.auth.isSignedIn())await window.puter.auth.signIn({attempt_temp_user_creation:false});setPuterUser(await window.puter.auth.getUser());}catch(error){setStatus(error instanceof Error?error.message:"No se pudo completar la conexión.");}finally{setConnecting(false);}}
async function disconnect(){if(!window.puter)return;await window.puter.auth.signOut();setPuterUser(null);setResult("");setStatus("Cuenta Puter desconectada de este navegador.");}
async function run(){if(!window.puter||!puterUser||!input.trim())return;setWorking(true);setResult("");setStatus("");try{const response=await window.puter.ai.chat([{role:"system",content:"Eres IA RADAR para el piloto municipal 0509 San José / Puerto San José, Escuintla. Ayuda a ordenar, resumir y analizar información de campaña. No inventes datos, no mezcles universos y no pidas ni reproduzcas DPI, teléfonos u otros datos personales. Toda recomendación requiere revisión humana."},{role:"user",content:`Tarea: ${selectedTask.label}.\n\n${input.trim()}\n\nEntrega una propuesta lista para revisar, sin frases promocionales.`}],{model:selectedTask.short?"gpt-5.4-nano":"gemini-3.1-flash-lite",max_tokens:selectedTask.short?1000:2400,temperature:selectedTask.short?0.3:0.45});const text=extractText(response).trim();if(!text)throw new Error("El servicio respondió sin texto. Probá de nuevo.");setResult(text);}catch(error){setStatus(error instanceof Error?error.message:"No se pudo completar la consulta.");}finally{setWorking(false);}}
async function copy(){if(!result)return;await navigator.clipboard.writeText(result);setCopied(true);window.setTimeout(()=>setCopied(false),1600);}
return <section className="radar-ai-assistant"><header className="radar-ai-statusbar"><div><span className="radar-ai-dot ready"/><p><b>Piloto 0509</b><small>Sesión RADAR autorizada</small></p></div>{puterUser?<div className="radar-ai-account"><span>Conectado como <b>{puterUser.username??"usuario Puter"}</b></span><button type="button" onClick={()=>void disconnect()}>Desconectar</button></div>:null}</header>{!puterUser?<div className="radar-ai-gate"><div><b>Conecta tu cuenta Puter.</b><span>RADAR no recibe ni guarda tu contraseña. La conexión vive en este navegador.</span></div><button type="button" disabled={!scriptReady||connecting} onClick={()=>void connect()}>{connecting?"Conectando…":scriptReady?"Conectar Puter":"Cargando conexión…"}</button></div>:<div className="radar-ai-workbench"><div className="radar-ai-starters"><small>PREGUNTAS PARA EMPEZAR</small>{starterQuestions.map((question)=><button type="button" key={question} onClick={()=>{setInput(question);setTask("consulta");}}>{question}</button>)}</div><div className="radar-ai-toolbar"><label><span>Tipo de ayuda</span><select value={task} onChange={(event)=>setTask(event.target.value as TaskValue)}>{taskOptions.map((option)=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label><p><span>{selectedTask.short?"OpenAI · tarea breve":"Puter · consulta ampliada"}</span><small>{selectedTask.short?"Rápido y puntual":"Mayor desarrollo"}</small></p></div><label className="radar-ai-prompt"><span>Información o consulta</span><textarea rows={8} value={input} maxLength={8000} onChange={(event)=>setInput(event.target.value)} placeholder="Escribe únicamente la información necesaria. No incluyas contactos, CUI ni datos personales."/><small>{input.length.toLocaleString("es-GT")} / 8,000</small></label><div className="radar-ai-actions"><button type="button" className="primary" disabled={working||!input.trim()} onClick={()=>void run()}>{working?"Preparando propuesta…":"Preparar propuesta"}</button><span>La respuesta no se guarda automáticamente.</span></div>{result?<article className="radar-ai-result"><header><b>Propuesta para revisar</b><div><button type="button" onClick={()=>void copy()}>{copied?"Copiado":"Copiar"}</button></div></header><div>{result}</div></article>:null}</div>}{status?<p className="radar-ai-message" role="status">{status}</p>:null}<footer className="radar-ai-boundary"><span>Uso interno</span><p>IA RADAR ayuda a ordenar, resumir y consultar. No sustituye la validación humana, no publica contenido y no debe recibir datos personales.</p></footer></section>}
function AiContent(){return <><section className="section-banner"><div className="section-banner-copy"><p>CAPA TRANSVERSAL</p><h1>IA RADAR</h1><span>Consultar, resumir y relacionar evidencia y operación sin duplicar datos</span></div></section><main className="radar-ai-page"><section className="ai-source-scope"><header><small>FUENTES CONECTADAS</small><h2>Una sola capa de consulta</h2><p>IA RADAR relaciona el contexto municipal y los resúmenes autorizados del Campaign Vault según los permisos del usuario.</p></header><div>{["Inteligencia Municipal","Estrategia","Directorio","Agenda","Mapa","Día D","Recursos","Pulso Electoral"].map((item)=><span key={item}>{item}</span>)}</div><aside><b>Recomendación de IA ≠ decisión aprobada</b><span>Briefs, prioridades, resúmenes y borradores deben ser revisados por la campaña antes de convertirse en instrucciones o mensajes oficiales.</span></aside></section><RadarAssistant/></main></>}
export function V70DirectAi0509(){const {municipalityCode}=useParams(); const consumer=resolveRadarConsumer(municipalityCode); if(!consumer||municipalityCode!=="0509")return <Navigate to="/" replace/>; return <MunicipalityProvider consumer={consumer}><V70DirectShell0509 active="ia-radar" eyebrow="ASISTENCIA INTERNA" topbarTitle="San José / Puerto San José · Escuintla"><AiContent/></V70DirectShell0509></MunicipalityProvider>}
