import { useState, type ReactNode } from "react";
import { Navigate, useParams } from "react-router-dom";
import { MunicipalityProvider } from "../context/MunicipalityContext";
import { resolveRadarConsumer } from "../data/radarConsumer";
import { V70DirectShell0509 } from "./V70DirectShell0509";

function InternalViews({ views }: { views: Array<{ key: string; label: string; content: ReactNode }> }) {
  const [active,setActive]=useState(views[0]?.key??""); const selected=views.find((view)=>view.key===active)??views[0]; if(!selected)return null;
  return <section className="internal-view-shell"><span className="internal-view-mobile-hint" aria-hidden="true">Desliza para ver más opciones →</span><nav className="internal-view-tabs" aria-label="Vistas internas de Recursos">{views.map((view)=><button key={view.key} className={view.key===selected.key?"active":""} onClick={()=>setActive(view.key)} type="button"><span>{view.label}</span></button>)}</nav><div className="internal-view-content" data-view={selected.key}>{selected.content}</div></section>;
}

const folders = [["Manuales","Protocolos operativos y electorales validados."],["Checklists","Apertura, jornada, cierre y control de evidencias."],["Plantillas","Formatos reutilizables para campaña y Día D."],["Tutoriales y Capacitación","Guías en distintos formatos para la campaña y utilización de RADAR."]] as const;
const resourceTypes = ["Vehículos","Sedes","Equipo audiovisual","Material promocional","Otros"] as const;

function ResourcesContent(){const [resourceType,setResourceType]=useState("Vehículos"); return <><section className="section-banner"><div className="section-banner-copy"><p>INVENTARIO OPERATIVO</p><h1>Recursos</h1><span>Documentos, activos físicos y archivos oficiales de campaña</span></div></section><InternalViews views={[
  {key:"materiales",label:"Materiales",content:<section className="resources-workspace"><header><small>BIBLIOTECA</small><h2>Documentos precargados</h2></header><div className="preloaded-resource-grid">{folders.map(([title,detail])=><article key={title}><i>▤</i><b>{title}</b><span>{detail}</span><button type="button">Abrir</button></article>)}</div></section>},
  {key:"fisicos",label:"Recursos físicos",content:<section className="resources-workspace"><header><small>BANCO DE RECURSOS</small><h2>Recursos físicos</h2><p>Vehículos, sedes, equipo audiovisual, materiales promocionales y otros activos.</p></header><section className="physical-bank"><div className="physical-resource-types">{resourceTypes.map((label)=><button type="button" key={label} className={resourceType===label?"active":""} onClick={()=>setResourceType(label)} aria-label={`Agregar ${label.toLowerCase()}`}><b>0</b><span>{label}</span><small><i>+</i> Agregar</small></button>)}</div><header className="physical-bank-bar"><div><small>BANCO DE RECURSOS</small><h2>{resourceType}</h2></div><button>+ Agregar {resourceType.toLowerCase()}</button></header><div className="physical-bank-list"><div className="agenda-empty"><b>No hay {resourceType.toLowerCase()} registrados.</b><button>Agregar el primero</button></div></div></section></section>},
  {key:"oficiales",label:"Archivos oficiales",content:<section className="resources-workspace"><header><small>CONEXIÓN CON COMUNICACIÓN, AGENDA Y DIRECTORIO</small><h2>Archivos oficiales</h2><p>Fotografías del candidato, materiales aprobados, logotipo del partido y fotografías de actividades.</p></header><section className="communication-library"><header><nav><button className="active">Todo</button><button>Fotografías oficiales</button><button>Logotipos</button><button>Actividades</button></nav><div><button className="secondary">+ Carpeta</button><button>+ Nueva carga</button></div></header><div className="communication-album"><div className="communication-empty"><b>Banco oficial listo para recibir piezas.</b><span>Carga fotografías, logotipos y materiales aprobados de campaña.</span><button>Nueva carga</button></div></div></section></section>}
]} /></>}

export function V70DirectResources0509(){const {municipalityCode}=useParams(); const consumer=resolveRadarConsumer(municipalityCode); if(!consumer||municipalityCode!=="0509") return <Navigate to="/" replace/>; return <MunicipalityProvider consumer={consumer}><V70DirectShell0509 active="recursos" eyebrow="OPERACIÓN" topbarTitle="San José / Puerto San José · Escuintla" accountRole="Dirección de campaña"><ResourcesContent/></V70DirectShell0509></MunicipalityProvider>;}
