import { useState } from "react";
import { Navigate, useParams } from "react-router-dom";
import { MunicipalityProvider } from "../context/MunicipalityContext";
import { resolveRadarConsumer } from "../data/radarConsumer";
import { V70DirectShell0509 } from "./V70DirectShell0509";

const electorStatuses = ["Sin contacto", "Contactado", "Interesado", "No interesado", "Voluntario", "Líder"] as const;
const contactTypes = ["Candidato", "Coordinador", "Fiscal", "Líder", "Voluntario", "Contacto"] as const;

function ElectorsDirectoryCanonical() {
  const [query,setQuery]=useState(""); const [dpi,setDpi]=useState(""); const [community,setCommunity]=useState(""); const [ageRange,setAgeRange]=useState(""); const [status,setStatus]=useState(""); const [affiliation,setAffiliation]=useState(""); const [responsible,setResponsible]=useState(""); const [role,setRole]=useState("");
  const clear=()=>{setQuery("");setDpi("");setCommunity("");setAgeRange("");setStatus("");setAffiliation("");setResponsible("");setRole("");};
  return <>
    <section className="elector-kpis" aria-label="Resumen del Directorio"><span><b>36,878</b><small>Registros</small></span><span><b>0</b><small>Contactos</small></span><span><b>0</b><small>Líderes</small></span><span><b>148</b><small>Comunidades</small></span></section>
    <section className="elector-filters"><label className="wide"><span>Nombre</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Nombre o palabras aproximadas" /></label><label><span>DPI</span><input inputMode="numeric" value={dpi} onChange={(event)=>setDpi(event.target.value)} placeholder="DPI completo" /></label><label><span>Comunidad</span><select value={community} onChange={(event)=>setCommunity(event.target.value)}><option value="">Todas</option></select></label><label><span>Edad estimada</span><select value={ageRange} onChange={(event)=>setAgeRange(event.target.value)}><option value="">Todas</option><option value="18-29">18–29</option><option value="30-44">30–44</option><option value="45-59">45–59</option><option value="60-">60 o más</option></select></label><label><span>Estado</span><select value={status} onChange={(event)=>setStatus(event.target.value)}><option value="">Todos</option>{electorStatuses.map((item)=><option key={item}>{item}</option>)}</select></label><label><span>Afiliado al partido</span><select value={affiliation} onChange={(event)=>setAffiliation(event.target.value)}><option value="">—</option><option value="SI">Sí</option><option value="NO">No</option></select></label><label><span>Responsable</span><select value={responsible} onChange={(event)=>setResponsible(event.target.value)}><option value="">Todos</option></select></label><label><span>Rol</span><input value={role} onChange={(event)=>setRole(event.target.value)} placeholder="Ej. fiscal o liderazgo" /></label><button type="button" onClick={clear}>Limpiar</button><button type="button" className="primary">+ Agregar contacto</button></section>
    <section className="elector-results"><header><div><small>RESULTADOS</small><h2>36,878 personas</h2></div><label>Por página<select defaultValue="25"><option value="25">25</option><option value="50">50</option></select></label></header><div className="elector-table" role="table"><div className="elector-row head" role="row"><span>Persona</span><span>Comunidad</span><span>Edad estimada</span><span>Estado</span><span>Contacto</span><span /></div><div className="elector-loading">No hay coincidencias con estos filtros.</div></div><footer><button disabled>← Anterior</button><span>Página <b>1</b> de 1,476</span><button>Siguiente →</button></footer></section>
  </>;
}

function TeamDirectoryCanonical(){const [query,setQuery]=useState(""); const [contactFilter,setContactFilter]=useState("all"); const [view,setView]=useState<"cards"|"table">("cards"); return <><section className="crm-controlbar"><label className="crm-search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar nombre, teléfono, comunidad o cargo" /></label><label><span>Tipo de contacto</span><select value={contactFilter} onChange={(event)=>setContactFilter(event.target.value)}><option value="all">Todos</option>{contactTypes.map((item)=><option key={item}>{item}</option>)}</select></label><button className="crm-bulk-carnets" type="button" disabled>↓ Carnets (0)</button><div className="crm-view-switch" aria-label="Cambiar vista"><button className={view==="cards"?"active":""} onClick={()=>setView("cards")}>Tarjetas</button><button className={view==="table"?"active":""} onClick={()=>setView("table")}>Lista</button></div></section><section className="crm-directory crm-directory-v2"><header><div><small>CAMPAIGN VAULT · PRIVADO</small><h2>0 contactos visibles</h2></div></header><div className="agenda-empty"><b>El Directorio está listo para recibir tu base.</b><span>Agrega el primer contacto del equipo.</span><div><button>Agregar contacto</button></div></div></section></>}

function DirectoryContent(){const [mode,setMode]=useState<"electors"|"team">("electors"); return <><section className="section-banner"><div className="section-banner-copy"><p>CRM</p><h1>Directorio</h1><span>{mode==="electors"?"Base electoral municipal y seguimiento":"Base de datos / contactos por tipo"}</span></div>{mode==="team"?<div className="section-banner-actions"><div className="crm-banner-actions"><button className="secondary">↓ Descargar Excel</button><button>+ Agregar contacto</button></div></div>:null}</section><nav className="directory-universe-tabs" aria-label="Universos del Directorio"><button className={mode==="electors"?"active":""} onClick={()=>setMode("electors")}><b>Posibles votantes</b><span>Base precargada del municipio</span></button><button className={mode==="team"?"active":""} onClick={()=>setMode("team")}><b>Equipo y responsables</b><span>Operación interna de campaña</span></button></nav>{mode==="electors"?<ElectorsDirectoryCanonical/>:<TeamDirectoryCanonical/>}</>}
export function V70DirectDirectory0509(){const {municipalityCode}=useParams(); const consumer=resolveRadarConsumer(municipalityCode); if(!consumer||municipalityCode!=="0509")return <Navigate to="/" replace/>; return <MunicipalityProvider consumer={consumer}><V70DirectShell0509 active="directorio" eyebrow="RELACIONES" topbarTitle="San José / Puerto San José · Escuintla"><DirectoryContent/></V70DirectShell0509></MunicipalityProvider>}
