import { useMemo, useState } from "react";
import { Link, Navigate, useParams } from "react-router-dom";
import { MunicipalityProvider } from "../context/MunicipalityContext";
import { resolveRadarConsumer } from "../data/radarConsumer";
import { V70DirectShell0509 } from "./V70DirectShell0509";

const electoralMilestones = [
  ["convocatoria", "22 ENE 2027", "Convocatoria a elecciones", "CANDIDATURA"], ["postulacion", "23 ENE–28 MAR", "Postulación e inscripción de candidatos", "CANDIDATURA"], ["ciudadanos", "20 MAR 2027", "Cierre de inscripción de ciudadanos", "OPERACIÓN"], ["campana-inicio", "29 MAR 2027", "Inicio del período de campaña electoral", "CAMPAÑA"], ["padron", "24–30 ABR", "Publicación del padrón electoral", "OPERACIÓN"], ["jrv-municipio", "28 ABR 2027", "Definición del número de JRV por municipio", "OPERACIÓN"], ["financiamiento", "28 MAY 2027", "Publicidad del financiamiento", "CAMPAÑA"], ["campana-cierre", "25 JUN · 12:00", "Cierre de campaña, propaganda y publicación de encuestas", "CAMPAÑA"], ["eleccion", "27 JUN 2027", "Elecciones generales", "OPERACIÓN"], ["revision", "28 JUN–2 JUL", "Audiencias de revisión de escrutinios", "CANDIDATURA"],
] as const;
function monthCells(month: Date) { const first=new Date(month.getFullYear(),month.getMonth(),1); const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(); const pad=(first.getDay()+6)%7; return [...Array<null>(pad).fill(null),...Array.from({length:count},(_,index)=>index+1)]; }
function AgendaContent() {
  const [view,setView]=useState<"calendar"|"list">("calendar"); const [month,setMonth]=useState(()=>new Date()); const days=useMemo(()=>monthCells(month),[month]); const now=new Date();
  return <>
    <section className="section-banner"><div className="section-banner-copy"><p>OPERACIÓN</p><h1>Agenda</h1><span>Actividades, responsables, participantes y compromisos</span></div><div className="section-banner-actions"><button type="button">+ Nueva actividad</button></div></section>
    <section className="agenda-next"><article className="empty"><div><small>PRÓXIMA ACTIVIDAD EN LA AGENDA</small><h2>No hay actividades programadas</h2><p>Crea una actividad para verla destacada aquí.</p></div><button type="button">+ Nueva actividad</button></article></section>
    <section className="agenda-viewbar"><div><button className={view==="calendar"?"active":""} onClick={()=>setView("calendar")}>Calendario</button><button className={view==="list"?"active":""} onClick={()=>setView("list")}>Lista</button></div><Link to="../mapa">Ver actividades en el mapa →</Link></section>
    <section className="agenda-workspace"><div className="agenda-calendar"><header><div><small>AGENDA COMPARTIDA</small><h2>{view==="calendar"?month.toLocaleDateString("es-GT",{month:"long",year:"numeric"}):"Próximas actividades"}</h2></div>{view==="calendar"?<nav><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>←</button><button onClick={()=>setMonth(new Date())}>Hoy</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>→</button></nav>:null}</header>{view==="calendar"?<div className="month-grid"><div className="month-week">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map((label)=><span key={label}>{label}</span>)}</div><div className="month-days">{days.map((day,index)=>day?<article className={day===now.getDate()&&month.getMonth()===now.getMonth()&&month.getFullYear()===now.getFullYear()?"today":""} key={day}><b>{day}</b></article>:<article className="blank" key={`b${index}`}/>)}</div></div>:<div className="agenda-empty"><b>No hay actividades próximas.</b><span>Crea una actividad con responsable del Directorio y participantes opcionales.</span><button>Crear actividad</button></div>}</div><aside><small>CALENDARIO ELECTORAL</small><h2>Guatemala 2027</h2><p className="electoral-note">Fechas preliminares del TSE, sujetas al decreto oficial de convocatoria.</p><div className="electoral-date-list">{electoralMilestones.map(([id,date,title,scope])=><article className="electoral-date" key={id}><time>{date}</time><b>{title}</b><span>{scope} · PRELIMINAR</span></article>)}</div><a href="https://tse.org.gt/comunicacion/noticias/tse-presenta-cronograma-electoral-preliminar-para-las-elecciones-generales-y-de-diputados-al-parlamento-centroamericano-2027" target="_blank" rel="noreferrer">Consultar fuente oficial TSE ↗</a></aside></section>
    <section className="commitments-section"><header><div><small>SEGUIMIENTO DE ACUERDOS</small><h2>Compromisos adquiridos</h2><p>Cada compromiso tiene responsable, fecha límite, prioridad y evidencia de cumplimiento.</p></div><button type="button">+ Nuevo compromiso</button></header><div className="commitment-kpis"><span><b>0</b> abiertos</span><span><b>0</b> vencidos</span><span><b>0</b> cumplidos</span></div><div className="commitment-list"><div className="agenda-empty"><b>No hay compromisos registrados.</b><span>Créalos al terminar una reunión o directamente desde este panel.</span><button type="button">Crear compromiso</button></div></div></section>
  </>;
}
export function V70DirectAgenda0509(){const {municipalityCode}=useParams(); const consumer=resolveRadarConsumer(municipalityCode); if(!consumer||municipalityCode!=="0509")return <Navigate to="/" replace/>; return <MunicipalityProvider consumer={consumer}><V70DirectShell0509 active="agenda" eyebrow="OPERACIÓN" topbarTitle="San José / Puerto San José · Escuintla"><AgendaContent/></V70DirectShell0509></MunicipalityProvider>}
