import { useState, type ReactNode } from "react";
import { Navigate, useParams } from "react-router-dom";
import { MunicipalityProvider } from "../context/MunicipalityContext";
import { resolveRadarConsumer } from "../data/radarConsumer";
import { V70DirectShell0509 } from "./V70DirectShell0509";

function InternalViews({ views }: { views: Array<{ key: string; label: string; content: ReactNode }> }) { const [active,setActive]=useState(views[0]?.key??""); const selected=views.find((view)=>view.key===active)??views[0]; if(!selected)return null; return <section className="internal-view-shell"><span className="internal-view-mobile-hint" aria-hidden="true">Desliza para ver más opciones →</span><nav className="internal-view-tabs" aria-label="Vistas internas de Recursos">{views.map((view)=><button key={view.key} className={view.key===selected.key?"active":""} onClick={()=>setActive(view.key)} type="button"><span>{view.label}</span></button>)}</nav><div className="internal-view-content" data-view={selected.key}>{selected.content}</div></section>; }
const folders = [["Manuales","Protocolos operativos y electorales validados."],["Checklists","Apertura, jornada, cierre y control de evidencias."],["Plantillas","Formatos reutilizables para campaña y Día D."],["Tutoriales y Capacitación","Guías en distintos formatos para la campaña y utilización de RADAR."]] as const;
const physicalTypes = [{key:"Vehículo",label:"Vehículos"},{key:"Sede",label:"Sedes"},{key:"Equipo audiovisual",label:"Equipo audiovisual"},{key:"Material promocional",label:"Material promocional"},{key:"Otro recurso",label:"Otros"}] as const;
const officialFolders = ["Fotografías oficiales","Logotipos","Piezas de campaña","Material para medios"] as const;

function Materials(){const [folder,setFolder]=useState<string|null>(null); return <><div className="preloaded-resource-grid">{folders.map(([title,detail])=><article key={title}><i>▤</i><b>{title}</b><span>{detail}</span><button type="button" onClick={()=>setFolder(title)}>Abrir</button></article>)}</div>{folder?<div className="agenda-modal" role="dialog" aria-modal="true"><section className="materials-folder-modal"><header><div><small>BIBLIOTECA · DOCUMENTOS PRECARGADOS</small><h2>{folder}</h2></div><button aria-label="Cerrar" onClick={()=>setFolder(null)}>×</button></header><div><p>La carpeta está lista. Los materiales aparecerán aquí cuando sean publicados por el superadministrador.</p></div></section></div>:null}</>}
function Physical(){const [active,setActive]=useState("Vehículo"); const [open,setOpen]=useState(false); const definition=physicalTypes.find((item)=>item.key===active)??physicalTypes[0]; const begin=(key:string)=>{setActive(key);setOpen(true);}; return <section className="physical-bank"><div className="physical-resource-types">{physicalTypes.map((item)=><button type="button" key={item.key} className={active===item.key?"active":""} onClick={()=>begin(item.key)} aria-label={`Agregar ${item.label.toLowerCase()}`}><b>0</b><span>{item.label}</span><small><i>+</i> Agregar</small></button>)}</div><header className="physical-bank-bar"><div><small>BANCO DE RECURSOS</small><h2>{definition.label}</h2></div><button onClick={()=>begin(active)}>+ Agregar {definition.label.toLowerCase()}</button></header><div className="physical-bank-list"><div className="agenda-empty"><b>No hay {definition.label.toLowerCase()} registrados.</b><button onClick={()=>begin(active)}>Agregar el primero</button></div></div>{open?<div className="agenda-modal" role="dialog" aria-modal="true"><form className="logistics-modal physical-resource-modal"><header><div><small>BANCO DE RECURSOS</small><h2>{definition.label}</h2></div><button type="button" aria-label="Cerrar" onClick={()=>setOpen(false)}>×</button></header><div className="logistics-form-grid"><label><span>Tipo</span><select defaultValue={active}><option value={active}>{definition.label.replace(/s$/,"")}</option><option value="OTRO">Otro</option></select></label><label className="wide"><span>Nombre</span><input placeholder="Nombre del recurso" /></label><label className="wide"><span>Notas</span><textarea rows={3}/></label></div><footer><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button type="button">Guardar recurso</button></footer></form></div>:null}</section>}
function Official(){const [folder,setFolder]=useState("Todos"); const [upload,setUpload]=useState(false); const [newFolder,setNewFolder]=useState(false); return <section className="communication-library"><header><nav><button className={folder==="Todos"?"active":""} onClick={()=>setFolder("Todos")}>Todo</button>{officialFolders.map((item)=><button className={folder===item?"active":""} key={item} onClick={()=>setFolder(item)}>{item}</button>)}</nav><div><button className="secondary" onClick={()=>setNewFolder(true)}>+ Carpeta</button><button onClick={()=>setUpload(true)}>+ Nueva carga</button></div></header><div className="communication-album"><div className="communication-empty"><b>Banco oficial listo para recibir piezas.</b><span>Carga fotografías, logotipos y materiales aprobados de campaña.</span><button onClick={()=>setUpload(true)}>Nueva carga</button></div></div>{newFolder?<div className="agenda-modal" role="dialog" aria-modal="true"><form className="simple-campaign-modal"><header><div><small>COMUNICACIÓN</small><h2>Nueva carpeta</h2></div><button type="button" onClick={()=>setNewFolder(false)}>×</button></header><label><span>Nombre de la carpeta</span><input autoFocus required /></label><footer><button type="button" onClick={()=>setNewFolder(false)}>Cancelar</button><button type="button">Crear carpeta</button></footer></form></div>:null}{upload?<div className="agenda-modal" role="dialog" aria-modal="true"><form className="simple-campaign-modal"><header><div><small>BANCO OFICIAL</small><h2>Nueva carga</h2></div><button type="button" onClick={()=>setUpload(false)}>×</button></header><label><span>Nombre de la pieza</span><input required /></label><label><span>Carpeta</span><select defaultValue={officialFolders[0]}>{officialFolders.map((item)=><option key={item}>{item}</option>)}</select></label><label><span>Archivo</span><input required type="file" accept="image/jpeg,image/png,image/webp,application/pdf" /></label><footer><button type="button" onClick={()=>setUpload(false)}>Cancelar</button><button type="button">Guardar pieza</button></footer></form></div>:null}</section>}
function ResourcesContent(){return <><section className="section-banner"><div className="section-banner-copy"><p>INVENTARIO OPERATIVO</p><h1>Recursos</h1><span>Documentos, activos físicos y archivos oficiales de campaña</span></div></section><InternalViews views={[{key:"materiales",label:"Materiales",content:<section className="resources-workspace"><header><small>BIBLIOTECA</small><h2>Documentos precargados</h2></header><Materials/></section>},{key:"fisicos",label:"Recursos físicos",content:<section className="resources-workspace"><header><small>BANCO DE RECURSOS</small><h2>Recursos físicos</h2><p>Vehículos, sedes, equipo audiovisual, materiales promocionales y otros activos.</p></header><Physical/></section>},{key:"oficiales",label:"Archivos oficiales",content:<section className="resources-workspace"><header><small>CONEXIÓN CON COMUNICACIÓN, AGENDA Y DIRECTORIO</small><h2>Archivos oficiales</h2><p>Fotografías del candidato, materiales aprobados, logotipo del partido y fotografías de actividades.</p></header><Official/></section>}]}/></>}
export function V70DirectResources0509(){const {municipalityCode}=useParams(); const consumer=resolveRadarConsumer(municipalityCode); if(!consumer||municipalityCode!=="0509") return <Navigate to="/" replace/>; return <MunicipalityProvider consumer={consumer}><V70DirectShell0509 active="recursos" eyebrow="OPERACIÓN" topbarTitle="San José / Puerto San José · Escuintla"><ResourcesContent/></V70DirectShell0509></MunicipalityProvider>;}
