import { useEffect, useMemo, useState } from "react";
import { Link, useParams, useSearchParams } from "react-router-dom";

type ReportMetric = { label: string; value: string; note: string };
type ReportSection = { key?: string; eyebrow: string; title: string; text?: string; items: string[] };
type ReportDefinition = { key: string; eyebrow: string; title: string; subtitle: string; summary: string; vault: "DATA VAULT" | "CAMPAIGN VAULT"; backHref: string; metrics: ReportMetric[]; sections: ReportSection[]; sources: string; landscape?: boolean };

const base = "/municipio/0509";
const common = { municipality: "San José / Puerto San José", department: "Escuintla", code: "0509", campaignType: "Campaña Alcaldía", candidateName: "Nombre Apellido" } as const;
const definitions: Record<string, ReportDefinition> = {
  inicio: { key:"inicio", eyebrow:"CENTRO DE CONTROL ELECTORAL 2027", title:"Resumen ejecutivo de campaña", subtitle:"San José / Puerto San José · Campaña Alcaldía", summary:"Lectura general del proyecto político, la planilla municipal y las tareas que requieren atención.", vault:"CAMPAIGN VAULT", backHref:base, metrics:[{label:"Integrantes de planilla",value:"12",note:"3 síndicos · 8 concejales"},{label:"Expedientes completos",value:"0",note:"Control legal preliminar"},{label:"Expedientes pendientes",value:"12",note:"Incluye documentos en revisión"},{label:"Municipio",value:"0509",note:"San José · Escuintla"}], sections:[{eyebrow:"PLANILLA MUNICIPAL",title:"Integración de la candidatura",items:["Candidato a alcalde: Nombre Apellido · PENDIENTE","Síndicos I–III: expedientes pendientes","Concejales I–VIII: expedientes pendientes"]},{eyebrow:"CONTROL EJECUTIVO",title:"Módulos conectados",items:["Inteligencia Municipal y Mapa Inteligente","Campaña, Agenda y Directorio","Legal, recursos, encuestas y control financiero"]}], sources:"Perfil de campaña y Campaign Vault · información de ejemplo pendiente de personalización administrativa." },
  "municipio-360": { key:"municipio-360", eyebrow:"EXPEDIENTE MUNICIPAL 360", title:"Inteligencia Municipal", subtitle:"Fotografía estratégica del municipio para definir mensajes y prioridades", summary:"Documento ejecutivo construido con fuentes públicas trazables, conservando el año y alcance territorial de cada dato.", vault:"DATA VAULT", backHref:`${base}/inteligencia`, metrics:[{label:"Población proyectada 2026",value:"72,156",note:"INE · proyección oficial"},{label:"Padrón activo 2026",value:"40,890",note:"21,531 mujeres · 19,359 hombres"},{label:"Centros electorales",value:"13",note:"103 JRV enlazadas"},{label:"Lugares poblados INE",value:"82",note:"81 con coordenadas"}], sections:[{key:"electoral",eyebrow:"LECTURA ELECTORAL",title:"Historial municipal",items:["Memorias oficiales procesadas: 2011, 2015, 2019 y 2023.","Ganadora municipal 2023: Odilia, partido VALOR.","TREP 2023 se conserva rotulado como preliminar y separado de la Memoria Electoral."]},{key:"center",eyebrow:"CENTRO SELECCIONADO",title:"Lectura centro por centro",items:["13 centros únicos y 103 JRV enlazadas.","38,934 electores 2023 enlazados a centros.","La ficha conserva electores, JRV, tipo y cobertura de actas."]},{key:"territory",eyebrow:"TERRITORIO",title:"Organización municipal",items:["4 microrregiones y 5 centralidades según PDM-OT.","20 COCODES de primer nivel y 25 de segundo nivel.","82 lugares INE: 81 con coordenadas y uno sin coordenadas."]},{key:"indicators",eyebrow:"INDICADORES MUNICIPALES",title:"Población e infraestructura",items:["62,801 habitantes en el Censo 2018; proyección 2026 de 72,156.","5 establecimientos MSPAS en la capa nacional validada.","76 registros educativos geoespaciales; la capa continúa siendo parcial."]},{key:"finance",eyebrow:"FINANZAS Y GESTIÓN",title:"Presupuesto, inversión y obras",items:["Ingresos municipales disponibles para 2016-2025.","Egresos comparables 2016-2023; Región V 2024 continúa pendiente.","7 obras municipales y 20 proyectos SNIP se mantienen como universos separados."]},{eyebrow:"REGLA DE DATOS",title:"Límites de interpretación",items:["Los vacíos nunca se convierten en cero.","No se mezclan escalas municipales, departamentales y nacionales.","No se suman universos de MINFIN, SNIP, CODEDE, municipalidad y Guatecompras."]}], sources:"TSE · INE · MINFIN · SEGEPLAN · MINEDUC · MSPAS · Guatecompras · CONRED." },
  estrategia: { key:"estrategia", eyebrow:"CAMPAÑA MUNICIPAL 2027", title:"Plan de campaña", subtitle:"San José / Puerto San José · Documento ejecutivo de uso interno", summary:"Concentra la ruta definida por la campaña, su FODA y los datos oficiales mínimos utilizados para orientar las decisiones.", vault:"CAMPAIGN VAULT", backHref:`${base}/estrategia`, metrics:[{label:"Padrón activo 2026",value:"40,890",note:"TSE · dato oficial"},{label:"Crecimiento desde 2023",value:"+5.02%",note:"+1,956 electores"},{label:"Centros electorales",value:"13",note:"103 JRV enlazadas"},{label:"Población proyectada",value:"72,156",note:"INE · 2026"}], sections:[{eyebrow:"USO DEL DOCUMENTO",title:"Versión oficial de trabajo",items:["Cada cambio conserva el usuario que lo registró y su fecha.","La campaña puede modificar el contenido y aprobar una nueva versión.","Los datos públicos y las decisiones privadas permanecen diferenciados."]},{eyebrow:"LÍMITE DE INTERPRETACIÓN",title:"Problemas municipales",items:["Las líneas base orientan preguntas y talking points.","Una cifra histórica debe validarse antes de presentarse como situación actual.","RADAR no convierte vacíos de información en cero ni inventa conclusiones."]}], sources:"Campaign Vault · Plan de campaña; TSE, INE y PDM-OT para el punto de partida." },
  directorio: { key:"directorio", eyebrow:"RELACIONES", title:"Directorio de campaña", subtitle:"Personas, responsables y contactos de la campaña", summary:"Directorio oficial para evitar nombres duplicados y mantener responsables consistentes entre Agenda, Mapa y Campaña.", vault:"CAMPAIGN VAULT", backHref:`${base}/directorio`, metrics:[{label:"Municipio",value:"0509",note:"San José · Escuintla"},{label:"Fuente",value:"CRM",note:"Directorio único"},{label:"Uso",value:"Interno",note:"Información privada"},{label:"Estado",value:"Vivo",note:"Datos al momento de generar"}], sections:[{eyebrow:"ORGANIZACIÓN",title:"Uso del directorio",items:["Asignar responsables en actividades y compromisos.","Relacionar líderes, equipo, planilla y contactos externos.","Conservar historial aunque una persona sea desactivada."]}], sources:"Campaign Vault · Directorio de campaña." },
  agenda: { key:"agenda", eyebrow:"OPERACIÓN", title:"Agenda de campaña", subtitle:"Actividades, responsables, participantes y compromisos", summary:"Documento operativo para compartir el calendario oficial del equipo y mantener una sola versión de cada actividad.", vault:"CAMPAIGN VAULT", backHref:`${base}/agenda`, metrics:[{label:"Municipio",value:"0509",note:"San José · Escuintla"},{label:"Elección",value:"2027",note:"Cronograma preliminar"},{label:"Integración",value:"Mapa",note:"Actividades geolocalizadas"},{label:"Responsables",value:"CRM",note:"Directorio oficial"}], sections:[{eyebrow:"CONTROL OPERATIVO",title:"Información incluida",items:["Fecha, hora y ubicación.","Responsable y participantes.","Estado, notas, ruta y compromisos relacionados."]}], sources:"Campaign Vault · Agenda y Directorio." },
  mapa: { key:"mapa", eyebrow:"OPERACIÓN TERRITORIAL", title:"Mapa Inteligente", subtitle:"Actividades, electores y comunidades prioritarias en una sola vista", summary:"Resumen ejecutivo de la operación territorial registrada en RADAR. El documento utiliza actividades y responsables vivos, no una captura cruda del mapa.", vault:"CAMPAIGN VAULT", backHref:`${base}/mapa`, landscape:true, metrics:[{label:"Territorio",value:"0509",note:"San José · Escuintla"},{label:"Centros electorales",value:"13",note:"Base territorial validada"},{label:"Lugares INE",value:"82",note:"81 georreferenciados"},{label:"Capas operativas",value:"3",note:"Electores, prioritarias y actividades"}], sections:[{eyebrow:"LECTURA TERRITORIAL",title:"Capas operativas",items:["Concentración de electores por sector.","Comunidades prioritarias y zonas sin cobertura.","Actividades registradas en Agenda.","Responsables y rutas de campaña."]},{eyebrow:"PRIVACIDAD",title:"Uso del documento",items:["No incluye información privada ajena al municipio.","Las coordenadas libres provienen de registros creados por la campaña.","Los lugares externos se diferencian de territorios oficiales RADAR."]}], sources:"Campaign Vault · Agenda y Mapa Inteligente; base territorial RADAR." },
  "dia-d": { key:"dia-d", eyebrow:"DÍA DE ELECCIÓN", title:"Día D", subtitle:"Centro de mando, fiscales, movilización, incidencias y reportes", summary:"Plantilla ejecutiva preparada para activarse cuando la candidatura y las reglas oficiales estén confirmadas.", vault:"CAMPAIGN VAULT", backHref:`${base}/dia-d`, metrics:[{label:"Centros",value:"13",note:"Cobertura objetivo"},{label:"JRV",value:"103",note:"Asignación pendiente"},{label:"Estado",value:"Plantilla",note:"Pendiente de activación"},{label:"Fuente",value:"TSE",note:"Reglas oficiales"}], sections:[{eyebrow:"COBERTURA",title:"Control previsto",items:["Asignación por centro y JRV.","Contacto, acreditación y asistencia.","Captura de actas, validación doble e incidencias."]}], sources:"TSE y Campaign Vault · sujeto a convocatoria y reglas oficiales." },
  recursos: { key:"recursos", eyebrow:"DOCUMENTOS", title:"Centro de recursos", subtitle:"Documentos, plantillas y archivos oficiales", summary:"Índice ejecutivo de recursos autorizados para que el equipo trabaje siempre con la versión correcta.", vault:"CAMPAIGN VAULT", backHref:`${base}/recursos`, metrics:[{label:"Control",value:"Único",note:"Una versión oficial"},{label:"Archivos",value:"Privados",note:"Por campaña"},{label:"Trazabilidad",value:"Activa",note:"Autor y fecha"},{label:"Exportación",value:"RADAR",note:"Formato institucional"}], sections:[{eyebrow:"BIBLIOTECA",title:"Tipos de recursos",items:["Actas y evidencias.","Plantillas rellenables.","Fotografías y materiales oficiales.","Informes ejecutivos RADAR."]}], sources:"Campaign Vault · Centro de recursos." },
  pulso: { key:"pulso", eyebrow:"INVESTIGACIÓN", title:"Pulso Electoral", subtitle:"Encuestas comparables, metodología visible y tendencias sin inventar certeza", summary:"Documento de lectura metodológica. Ninguna simulación visual se presenta como encuesta o resultado electoral.", vault:"CAMPAIGN VAULT", backHref:`${base}/pulso`, metrics:[{label:"Municipio",value:"0509",note:"San José · Escuintla"},{label:"Estado",value:"Plantilla",note:"Sin encuesta cargada"},{label:"Método",value:"Visible",note:"Toda medición debe documentarse"},{label:"Uso",value:"Interno",note:"Interpretación separada de datos"}], sections:[{eyebrow:"GUARDRAIL",title:"Lectura responsable",items:["No es una encuesta ni un resultado electoral.","Toda medición debe mostrar metodología, fecha y universo.","RADAR separa evidencia, interpretación y recomendación."]}], sources:"Campaign Vault · encuestas y registros autorizados." },
  "ia-radar": { key:"ia-radar", eyebrow:"ASISTENTE MUNICIPAL", title:"IA RADAR", subtitle:"Consultas, borradores y memoria autorizada", summary:"Ficha del asistente municipal y de los límites de información que puede utilizar.", vault:"CAMPAIGN VAULT", backHref:`${base}/ia-radar`, metrics:[{label:"Municipio",value:"0509",note:"Contexto autorizado"},{label:"Datos públicos",value:"Trazables",note:"Data Vault"},{label:"Datos privados",value:"Aislados",note:"Campaign Vault"},{label:"Estado",value:"Plantilla",note:"Próxima activación"}], sections:[{eyebrow:"ALCANCE",title:"Funciones previstas",items:["Consultar el municipio con fuentes.","Preparar resúmenes y documentos.","Utilizar memoria privada solo con permisos.","Diferenciar hechos, interpretación y recomendación."]}], sources:"RADAR Data Vault y Campaign Vault según permisos." },
  configuracion: { key:"configuracion", eyebrow:"CUENTA", title:"Configuración y seguridad", subtitle:"Usuarios, permisos y privacidad", summary:"Resumen de las reglas de acceso y aislamiento aplicables a la campaña y al municipio.", vault:"CAMPAIGN VAULT", backHref:`${base}/configuracion`, metrics:[{label:"Municipio",value:"0509",note:"Exclusividad territorial"},{label:"Campaña",value:"1",note:"Un cliente por elección"},{label:"Acceso",value:"Por rol",note:"Permisos diferenciados"},{label:"Datos",value:"Aislados",note:"Por campaña"}], sections:[{eyebrow:"SEGURIDAD",title:"Reglas principales",items:["Usuarios administrados por campaña.","Roles diferenciados y mínimo acceso necesario.","Campaign Vault separado del Data Vault.","Historial de cambios en información sensible."]}], sources:"Configuración interna de RADAR." },
};

function chunks<T>(items:T[], size:number){return Array.from({length:Math.ceil(items.length/size)},(_,index)=>items.slice(index*size,index*size+size));}
function reportCode(definition:ReportDefinition){return `RADAR-${common.code}-${definition.key.toUpperCase().replace(/[^A-Z0-9]+/g,"-")}`;}
function Brand({dark=false}:{dark?:boolean}){const file=dark?"radar-electoral-logo-horizontal-oscuro-transparente.svg":"radar-electoral-logo-horizontal-claro.svg"; const baseUrl=import.meta.env.BASE_URL||"/"; return <div className="report-brand"><img src={`${baseUrl}brand/${file}`} alt="RADAR Electoral"/></div>}
function PageHeader({definition}:{definition:ReportDefinition}){return <header className="report-page-header"><Brand/><div><b>{definition.title}</b><span>{common.municipality} · {common.code}</span></div></header>}
function PageFooter({definition,page,total}:{definition:ReportDefinition;page:number;total:number}){return <footer className="report-page-footer"><span>{definition.vault} · {reportCode(definition)}</span><b>{page} / {total}</b></footer>}
function Sheet({definition,page,total,children,cover=false}:{definition:ReportDefinition;page:number;total:number;children:React.ReactNode;cover?:boolean}){return <section className={`report-sheet ${cover?"cover":""} ${definition.landscape&&!cover?"landscape":""}`}>{!cover?<PageHeader definition={definition}/>:null}<div className="report-page-body">{children}</div><PageFooter definition={definition} page={page} total={total}/></section>}
function SectionCard({section}:{section:ReportSection}){return <article className="report-section-card"><small>{section.eyebrow}</small><h3>{section.title}</h3>{section.text?<p>{section.text}</p>:null}<ul>{section.items.map((item)=><li key={item}>{item}</li>)}</ul></article>}

export function V70DirectReport0509(){
  const {section="inicio"}=useParams();
  const [searchParams]=useSearchParams();
  const definition=definitions[section]??definitions.inicio;
  const [generatedAt,setGeneratedAt]=useState("");
  const [copyLabel,setCopyLabel]=useState("Copiar enlace");
  useEffect(()=>{setGeneratedAt(new Intl.DateTimeFormat("es-GT",{dateStyle:"long",timeStyle:"short"}).format(new Date()));},[]);
  const blocks=useMemo(()=>searchParams.get("blocks")?.split(",").filter(Boolean)??[],[searchParams]);
  const parts=useMemo(()=>{const value=searchParams.get("parts")?.split(",").filter(Boolean)??[];return value.length?value:["summary","metrics","sections","records","trace"]},[searchParams]);
  const selectionContext=definition.key==="municipio-360"?[searchParams.get("election")?`Elección: ${searchParams.get("election")!.replaceAll("_"," ")}`:"",searchParams.get("center")?`Centro: CV ${searchParams.get("center")}`:""].filter(Boolean).join(" · "):"";
  const visibleSections=definition.sections.filter((item)=>parts.includes("sections")&&(!item.key||definition.key!=="municipio-360"||!blocks.length||blocks.includes(item.key)));
  const sectionPages=chunks(visibleSections,definition.landscape?4:3);
  const summaryIncluded=parts.includes("summary")||parts.includes("metrics")||parts.includes("trace");
  const total=1+(summaryIncluded?1:0)+sectionPages.length;
  async function copy(){try{await navigator.clipboard.writeText(window.location.href);setCopyLabel("Enlace copiado");window.setTimeout(()=>setCopyLabel("Copiar enlace"),1800);}catch{setCopyLabel("Copiar enlace");}}
  function print(){document.title=`${reportCode(definition)} · ${definition.title}`;window.print();}
  return <main className="report-shell">
    <nav className="report-actions" aria-label="Acciones del informe"><Link to={definition.backHref}>← Volver al módulo</Link><div><button onClick={copy}>{copyLabel}</button><button className="primary" onClick={print}>Guardar / Imprimir PDF</button></div></nav>
    <div className="report-document">
      <Sheet definition={definition} page={1} total={total} cover><div className="report-cover-top"><Brand dark/><span>{definition.vault}</span></div><div className="report-cover-main"><small>{definition.eyebrow}</small><h1>{definition.title}</h1><p>{definition.subtitle}</p><div className="report-cover-rule"/><div className="report-cover-project"><i/><div><small>{common.campaignType.toUpperCase()}</small><b>{common.candidateName}</b><span>{common.municipality} · {common.department}</span></div><i/></div></div><div className="report-cover-meta"><div><span>Documento</span><b>{reportCode(definition)}</b></div><div><span>Generado</span><b>{generatedAt||"Preparando fecha…"}</b></div><div><span>Clasificación</span><b>{definition.vault==="CAMPAIGN VAULT"?"USO INTERNO Y CONFIDENCIAL":"FUENTES PÚBLICAS TRAZABLES"}</b></div></div></Sheet>
      {summaryIncluded?<Sheet definition={definition} page={2} total={total}><div className="report-title-block"><small>RESUMEN EJECUTIVO</small><h2>{definition.title}</h2>{parts.includes("summary")?<p>{definition.summary}</p>:null}{selectionContext?<em>{selectionContext}</em>:null}</div>{parts.includes("metrics")?<div className="report-metrics">{definition.metrics.map((metric)=><article key={metric.label}><small>{metric.label}</small><b>{metric.value}</b><span>{metric.note}</span></article>)}</div>:null}{parts.includes("trace")?<div className="report-trace"><span>FUENTES Y TRAZABILIDAD</span><p>{definition.sources}</p></div>:null}</Sheet>:null}
      {sectionPages.map((page,index)=><Sheet key={index} definition={definition} page={2+(summaryIncluded?1:0)+index} total={total}><div className="report-section-grid">{page.map((item)=><SectionCard key={`${item.eyebrow}-${item.title}`} section={item}/>)}</div></Sheet>)}
    </div>
  </main>;
}
