import { useEffect, useState, type ReactNode } from "react";
import { createPortal } from "react-dom";
import { useMunicipalityContext } from "../context/MunicipalityContext";

function InternalViews({ views }: { views: Array<{ key: string; label: string; content: ReactNode }> }) {
  const [active,setActive]=useState(views[0]?.key??""); const selected=views.find((view)=>view.key===active)??views[0]; if(!selected)return null;
  return <section className="internal-view-shell"><span className="internal-view-mobile-hint" aria-hidden="true">Desliza para ver más opciones →</span><nav className="internal-view-tabs" aria-label="Vistas internas de Recursos">{views.map((view)=><button key={view.key} className={view.key===selected.key?"active":""} onClick={()=>setActive(view.key)} type="button"><span>{view.label}</span></button>)}</nav><div className="internal-view-content" data-view={selected.key}>{selected.content}</div></section>;
}

const folders = [["Manuales","Protocolos operativos y electorales validados."],["Checklists","Apertura, jornada, cierre y control de evidencias."],["Plantillas","Formatos reutilizables para campaña y Día D."],["Tutoriales y Capacitación","Guías en distintos formatos para la campaña y utilización de RADAR."]] as const;
const resourceTypes = ["Vehículos","Sedes","Equipo audiovisual","Material promocional","Otros"] as const;

function CanonicalResources(){const [resourceType,setResourceType]=useState("Vehículos"); return <><section className="section-banner"><div className="section-banner-copy"><p>INVENTARIO OPERATIVO</p><h1>Recursos</h1><span>Documentos, activos físicos y archivos oficiales de campaña</span></div></section><InternalViews views={[
  {key:"materiales",label:"Materiales",content:<section className="resources-workspace"><header><small>BIBLIOTECA</small><h2>Documentos precargados</h2></header><div className="preloaded-resource-grid">{folders.map(([title,detail])=><article key={title}><i>▤</i><b>{title}</b><span>{detail}</span><button type="button">Abrir</button></article>)}</div></section>},
  {key:"fisicos",label:"Recursos físicos",content:<section className="resources-workspace"><header><small>BANCO DE RECURSOS</small><h2>Recursos físicos</h2><p>Vehículos, sedes, equipo audiovisual, materiales promocionales y otros activos.</p></header><section className="physical-bank"><div className="physical-resource-types">{resourceTypes.map((label)=><button type="button" key={label} className={resourceType===label?"active":""} onClick={()=>setResourceType(label)} aria-label={`Agregar ${label.toLowerCase()}`}><b>0</b><span>{label}</span><small><i>+</i> Agregar</small></button>)}</div><header className="physical-bank-bar"><div><small>BANCO DE RECURSOS</small><h2>{resourceType}</h2></div><button>+ Agregar {resourceType.toLowerCase()}</button></header><div className="physical-bank-list"><div className="agenda-empty"><b>No hay {resourceType.toLowerCase()} registrados.</b><button>Agregar el primero</button></div></div></section></section>},
  {key:"oficiales",label:"Archivos oficiales",content:<section className="resources-workspace"><header><small>CONEXIÓN CON COMUNICACIÓN, AGENDA Y DIRECTORIO</small><h2>Archivos oficiales</h2><p>Fotografías del candidato, materiales aprobados, logotipo del partido y fotografías de actividades.</p></header><section className="communication-library"><header><nav><button className="active">Todo</button><button>Fotografías oficiales</button><button>Logotipos</button><button>Actividades</button></nav><div><button className="secondary">+ Carpeta</button><button>+ Nueva carga</button></div></header><div className="communication-album"><div className="communication-empty"><b>Banco oficial listo para recibir piezas.</b><span>Carga fotografías, logotipos y materiales aprobados de campaña.</span><button>Nueva carga</button></div></div></section></section>}
]} /></>}

export function V70ResourcesParityBridge(){const {municipality_code}=useMunicipalityContext(); const [host,setHost]=useState<HTMLElement|null>(null); useEffect(()=>{if(municipality_code!=="0509")return; const main=document.querySelector<HTMLElement>(".portal-main"); const topbar=main?.querySelector<HTMLElement>(":scope > header.portal-topbar"); if(!main||!topbar)return; const existing=main.querySelector<HTMLElement>("[data-v70-resources-slot]"); const slot=existing??document.createElement("div"); slot.dataset.v70ResourcesSlot="true"; slot.style.display="contents"; if(!existing)topbar.insertAdjacentElement("afterend",slot); const previous=Array.from(main.children).filter((node):node is HTMLElement=>node instanceof HTMLElement&&node!==topbar&&node!==slot).map((node)=>({node,hidden:node.hidden===true})); previous.forEach(({node})=>{node.hidden=true}); setHost(slot); return()=>{previous.forEach(({node,hidden})=>{node.hidden=hidden}); if(!existing)slot.remove(); setHost(null);};},[municipality_code]); return host?createPortal(<CanonicalResources/>,host):null;}
