import { useState, type FormEvent } from "react";
import { useDismissibleDialog } from "./useDismissibleDialog";
import { Link } from "react-router-dom";
import { uploadSharedResource, type AdminSnapshot } from "./radarAdminApi";
type Row=Record<string,unknown>;
type Props={snapshot:AdminSnapshot;action:(name:string,input:Row)=>Promise<boolean>;busy:boolean;refresh:()=>Promise<void>};
export function DailyHome({snapshot}:{snapshot:AdminSnapshot}) {
 const today=new Date().toISOString().slice(0,10);
 const assigned=new Set(snapshot.contracts.filter(c=>["ACTIVE","RESERVED","SUSPENDED"].includes(String(c.status))&&(!c.valid_until||String(c.valid_until)>=today)).map(c=>c.municipality_code));
 const metrics=[{label:"Municipios con contrato",value:assigned.size,to:"/admin/municipios?estado=assigned",detail:"Ver clientes y equipos",tone:"petrol"},{label:"Municipios sin contrato registrado",value:snapshot.municipalities.filter(m=>!assigned.has(m.municipality_code)).length,to:"/admin/municipios?estado=available",detail:"Explorar disponibilidad",tone:"sage"},{label:"Usuarios asignados a campañas",value:new Set((snapshot.campaign_members??[]).map(m=>m.user_id)).size,to:"/admin/equipos",detail:"Ver usuarios y sus municipios",tone:"purple"}];
 return <><div className="client-metrics">{metrics.map(m=><Link className={`client-metric ${m.tone}`} to={m.to} key={m.to}><span>{m.label}</span><strong>{m.value.toLocaleString("es-GT")}</strong><div className="client-metric-link">{m.detail}<span aria-hidden="true">↗</span></div></Link>)}</div><div className="client-section-title"><div><small>OPERACIÓN DIARIA</small><h2>Todo a tu alcance</h2></div><p>Clientes, contenido y comunicación en un solo lugar.</p></div><div className="client-home-links">{[["municipios","◎","Clientes y municipios","Asignar un municipio y acompañar a cada equipo."],["recursos","▣","Biblioteca de recursos","Documentos listos para los municipios."],["pulso","◒","Encuestas electorales","Candidatos y resultados por territorio."],["avisos","◇","Comunicación","Mensajes oportunos para tus clientes."],["demos","↻","Demostraciones","Preparar un entorno limpio para presentar RADAR."],["rtd","▤","Día D · RTD nacional","Fiscales, recepción de actas y votos por elección."]].map(([path,icon,title,detail],i)=><Link to={`/admin/${path}`} key={path}><div className="client-tile-top"><b aria-hidden="true">{icon}</b><small>0{i+1}</small></div><strong>{title}</strong><span>{detail}</span><em>Ir a {title.toLowerCase()} <i aria-hidden="true">→</i></em></Link>)}</div></>;
}
export function AssignedUsers({snapshot}:{snapshot:AdminSnapshot}) {
 const [query,setQuery]=useState("");
 const rows=(snapshot.campaign_members??[]).map(m=>({member:m,user:snapshot.users.find(u=>u.id===m.user_id),campaign:snapshot.campaigns.find(c=>c.id===m.campaign_id)})).filter(r=>`${r.user?.email??""} ${r.campaign?.name??""} ${r.campaign?.municipality_code??""}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="client-toolbar"><label>Buscar en los equipos<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Correo, campaña o municipio"/></label><span>{rows.length} asignaciones</span></div><div className="client-team-list">{rows.map(({member,user,campaign})=><article className="client-member" key={`${member.campaign_id}-${member.user_id}`}><div><strong>{String(user?.email??"Usuario")}</strong><small>{String(campaign?.name??"Campaña")} · {String(campaign?.municipality_code??"")} · {({campaign_admin:"Administrador",campaign_editor:"Editor",campaign_viewer:"Consulta",demo_admin:"Administrador demo",demo_viewer:"Consulta demo"} as Record<string,string>)[String(member.member_role)]??String(member.member_role)}</small></div><Link to={campaign?.is_demo?"/admin/demos":`/admin/municipios?municipio=${campaign?.municipality_code??""}`}>Ver ficha →</Link></article>)}</div>{!rows.length&&<p>No hay asignaciones que coincidan con la búsqueda.</p>}</>;
}

export function ContentWorkspace({snapshot,action,busy,refresh,kind}:{kind:"resource"|"notice"}&Props){
 const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [preview,setPreview]=useState<Row|null>(null);
 useDismissibleDialog(Boolean(open||preview),()=>{setOpen(false);setPreview(null);},saving||busy);
 const items=(snapshot.shared_content??[]).filter(c=>c.kind===kind);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const data=new FormData(event.currentTarget);const values=Object.fromEntries(data);delete values.file;
 for(const key of ["starts_at","ends_at"])if(values[key])values[key]=new Date(String(values[key])).toISOString();
 try{if(kind==="resource"){const file=data.get("file");if(!(file instanceof File)||!file.size)throw new Error("Selecciona un archivo");await uploadSharedResource(file,values);await refresh();setOpen(false);}else if(await action("save_notice",values))setOpen(false);}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar");}finally{setSaving(false);}}
 return <><div className="client-toolbar"><p>{kind==="resource"?"Sube una vez. Publica en los municipios seleccionados. Cada archivo conserva su versión.":"Los avisos publicados aparecen una vez por usuario dentro de su vigencia. Horarios según tu dispositivo."}</p><button className="superadmin-primary" onClick={()=>setOpen(true)}>{kind==="resource"?"+ Subir documento":"+ Crear aviso"}</button></div>
  <div className="client-grid">{items.map(item=><article className="client-card" key={String(item.id)}><span className="client-pill">{item.status==="DRAFT"?"Borrador":item.status==="PUBLISHED"?"Publicado":"Archivado"}</span><h3>{String(item.title)}</h3><p>{String(item.category??"Aviso RADAR")} · {item.municipality_code?`Municipio ${item.municipality_code}`:"Todos los municipios"}</p><p>{String(item.file_name??item.body).slice(0,150)}</p><div className="client-actions"><button onClick={()=>setPreview(item)}>Revisar</button>{item.status!=="ARCHIVED"&&<button disabled={busy} onClick={()=>void action("archive_content",{id:item.id})}>Retirar</button>}</div></article>)}</div>{!items.length&&<div className="client-callout"><h3>{kind==="resource"?"Tu biblioteca empieza aquí":"Sin avisos todavía"}</h3><p>Crea un borrador y revísalo antes de publicarlo.</p></div>}
  {(open||preview)&&<div className="client-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving&&!busy){setOpen(false);setPreview(null);}}}><section className="client-drawer" role="dialog" aria-modal="true" aria-label={kind==="resource"?"Documento":"Aviso"}><header><h2>{preview?"Revisar publicación":kind==="resource"?"Subir documento":"Crear aviso"}</h2><button disabled={saving||busy} onClick={()=>{setOpen(false);setPreview(null);}}>×</button></header><div className="client-body">{preview?<><h3>{String(preview.title)}</h3><p style={{whiteSpace:"pre-wrap"}}>{String(preview.body)}</p><p>Destino: {String(preview.municipality_code??"Todos los municipios")}</p><p>Desde: {new Date(String(preview.starts_at)).toLocaleString("es-GT")}<br/>Hasta: {preview.ends_at?new Date(String(preview.ends_at)).toLocaleString("es-GT"):"Sin fecha final"}</p>{preview.file_name&&<p>Archivo: {String(preview.file_name)} · versión {String(preview.version)}</p>}{preview.status!=="PUBLISHED"&&<button className="superadmin-primary" disabled={busy} onClick={async()=>{if(await action("publish_content",{id:preview.id}))setPreview(null);}}>Publicar</button>}</>:<form className="superadmin-form" onSubmit={submit}><label>Título<input name="title" required maxLength={150}/></label><label>{kind==="resource"?"Descripción":"Mensaje"}<textarea name="body" required maxLength={4000}/></label>{kind==="resource"&&<><label>Carpeta<select name="category">{["Manuales","Checklists","Plantillas","Tutoriales y Capacitación"].map(c=><option key={c}>{c}</option>)}</select></label><label>Versión<input name="version" defaultValue="1" required/></label><label>Archivo · máximo 25 MB<input name="file" type="file" accept=".pdf,.docx,.xlsx,.pptx,.png,.jpg,.jpeg,.webp,.mp4" required/></label></>}
   <label>Destinatarios<select name="municipality_code"><option value="">Todos los municipios</option>{snapshot.municipalities.map(m=><option key={m.municipality_code} value={m.municipality_code}>{m.municipality_name} · {m.department_name}</option>)}</select></label><label>Inicio de publicación<input type="datetime-local" name="starts_at"/></label><label>Fin de publicación<input type="datetime-local" name="ends_at" required={kind==="notice"}/></label><p>Se guardará como borrador. Podrás revisar el contenido y los destinatarios antes de publicarlo.</p>{error&&<p role="alert">{error}</p>}<button className="superadmin-primary" disabled={saving||busy}>{saving?"Guardando…":"Guardar borrador"}</button></form>}</div></section></div>}
 </>;
}
export function DemoWorkspace({snapshot,action,busy}:Omit<Props,"refresh">){const [selected,setSelected]=useState<Row|null>(null);useDismissibleDialog(Boolean(selected),()=>setSelected(null),busy);return <><p>El reinicio vacía los registros privados de la demo en QA. Conserva datos oficiales, usuarios y una copia interna de los registros eliminados.</p><div className="client-grid">{snapshot.campaigns.filter(c=>c.is_demo).map(c=><article className="client-card" key={String(c.id)}><span className="client-pill">Demo</span><h3>{String(c.name)}</h3><p>{String(c.municipality_code)}</p><button onClick={()=>setSelected(c)}>Reiniciar datos privados</button></article>)}</div>{selected&&<div className="client-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setSelected(null);}}><section className="client-drawer" role="dialog" aria-modal="true" aria-label="Reiniciar demo"><header><h2>Reiniciar demostración</h2><button disabled={busy} onClick={()=>setSelected(null)}>×</button></header><form className="client-body superadmin-form" onSubmit={async e=>{e.preventDefault();if(await action("reset_demo",{campaign_id:selected.id,...Object.fromEntries(new FormData(e.currentTarget))}))setSelected(null);}}><p>Se vaciarán contactos, actividades, candidatos, fiscales, incidencias y resultados de esta demo. No se modifican campañas reales.</p><label>Escribe {String(selected.name)}<input name="confirmation" required/></label><button className="superadmin-primary" disabled={busy}>Confirmar reinicio</button></form></section></div>}</>;}
