import { resourceAccept, validateResource } from "../data/resourceFormats";
import { useRef, useState, type FormEvent } from "react";
import { useDismissibleDialog } from "./useDismissibleDialog";
import { Link } from "react-router-dom";
import { uploadSharedResource, type AdminSnapshot } from "./radarAdminApi";
type Row=Record<string,unknown>;
type Props={snapshot:AdminSnapshot;action:(name:string,input:Row)=>Promise<boolean>;busy:boolean;refresh:()=>Promise<void>};
export function DailyHome({snapshot}:{snapshot:AdminSnapshot}) {
 const today=new Date().toISOString().slice(0,10);
 const assigned=new Set(snapshot.contracts.filter(c=>["ACTIVE","RESERVED","SUSPENDED"].includes(String(c.status))&&(!c.valid_until||String(c.valid_until)>=today)).map(c=>c.municipality_code));
 const metrics=[{label:"Municipios con contrato",value:assigned.size,to:"/admin/municipios?estado=assigned",detail:"Ver clientes y equipos",tone:"petrol"},{label:"Municipios sin contrato registrado",value:snapshot.municipalities.filter(m=>!assigned.has(m.municipality_code)).length,to:"/admin/municipios?estado=available",detail:"Explorar disponibilidad",tone:"sage"},{label:"Usuarios asignados a campañas",value:new Set((snapshot.campaign_members??[]).map(m=>m.user_id)).size,to:"/admin/equipos",detail:"Ver usuarios y sus municipios",tone:"purple"}];
 return <><div className="client-metrics">{metrics.map(m=><Link className={`client-metric ${m.tone}`} to={m.to} key={m.to}><span>{m.label}</span><strong>{m.value.toLocaleString("es-GT")}</strong><div className="client-metric-link">{m.detail}<span aria-hidden="true">↗</span></div></Link>)}</div><div className="client-section-title"><div><small>OPERACIÓN DIARIA</small><h2>Todo a tu alcance</h2></div><p>Clientes, contenido y comunicación en un solo lugar.</p></div><div className="client-home-links">{[["municipios","◎","Clientes y municipios","Asignar un municipio y acompañar a cada equipo."],["recursos","▣","Biblioteca de recursos","Documentos listos para los municipios."],["pulso","◒","Encuestas electorales","Candidatos y resultados por territorio."],["avisos","◇","Comunicación","Mensajes oportunos para tus clientes."],["demos","↻","Demostraciones","Preparar un entorno limpio para presentar RADAR."],["rtd","▤","Día D · RTD nacional","Fiscales, recepción de actas y votos por elección."]].map(([path,icon,title,detail],i)=><Link to={`/admin/${path}`} key={path}><div className="client-tile-top"><b aria-hidden="true">{icon}</b><small>0{i+1}</small></div><strong>{title}</strong><span>{detail}</span><em>Ir a {title.toLowerCase()} <i aria-hidden="true">→</i></em></Link>)}</div></>;
}
export function AssignedUsers({snapshot}:{snapshot:AdminSnapshot}) {
 const [query,setQuery]=useState("");
 const rows=(snapshot.campaign_members??[]).map(m=>({member:m,user:snapshot.users.find(u=>u.id===m.user_id),campaign:snapshot.campaigns.find(c=>c.id===m.campaign_id)})).filter(r=>`${r.user?.email??""} ${r.campaign?.name??""} ${r.campaign?.municipality_code??""}`.toLowerCase().includes(query.toLowerCase()));
 return <><div className="client-toolbar"><label>Buscar en los equipos<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Correo, campaña o municipio"/></label><span>{rows.length} asignaciones</span></div><div className="client-team-list">{rows.map(({member,user,campaign})=><article className="client-member" key={`${member.campaign_id}-${member.user_id}`}><div><strong>{String(user?.email??"Usuario")}</strong><small>{String(campaign?.name??"Campaña")} · {String(campaign?.municipality_code??"")} · {({campaign_admin:"Administrador",campaign_editor:"Editor",campaign_viewer:"Consulta",demo_admin:"Administrador demo",demo_viewer:"Consulta demo"} as Record<string,string>)[String(member.member_role)]??String(member.member_role)}</small></div><Link to={campaign?.is_demo?"/admin/demos":`/admin/municipios?municipio=${campaign?.municipality_code??""}`}>Ver ficha →</Link></article>)}</div>{!rows.length&&<p>No hay asignaciones que coincidan con la búsqueda.</p>}</>;
}

export function ContentWorkspace({snapshot,action,busy,refresh,kind}:{kind:"resource"|"notice"}&Props){
 const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [preview,setPreview]=useState<Row|null>(null);const [deleting,setDeleting]=useState<Row|null>(null);
 useDismissibleDialog(Boolean(open||preview||deleting),()=>{setOpen(false);setPreview(null);setDeleting(null);},saving||busy);
 const items=(snapshot.shared_content??[]).filter(c=>c.kind===kind);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const data=new FormData(event.currentTarget);const values=Object.fromEntries(data);delete values.file;
 for(const key of ["starts_at","ends_at"])if(values[key])values[key]=new Date(String(values[key])).toISOString();
 try{if(kind==="resource"){const file=data.get("file");if(!(file instanceof File)||!file.size)throw new Error("Selecciona un archivo");validateResource(file);await uploadSharedResource(file,values);await refresh();setOpen(false);}else if(await action("save_notice",values))setOpen(false);}catch(e){setError(e instanceof Error?e.message:"No se pudo guardar");}finally{setSaving(false);}}
 return <><div className="client-toolbar"><p>{kind==="resource"?"Sube una vez. Publica en los municipios seleccionados. Cada archivo conserva su versión.":"Los avisos publicados aparecen una vez por usuario dentro de su vigencia. Horarios según tu dispositivo."}</p><button className="superadmin-primary" onClick={()=>setOpen(true)}>{kind==="resource"?"+ Subir documento":"+ Crear aviso"}</button></div>
  <div className="client-grid">{items.map(item=><article className="client-card" key={String(item.id)}><span className="client-pill">{item.status==="DRAFT"?"Borrador":item.status==="PUBLISHED"?"Publicado":"Archivado"}</span><h3>{String(item.title)}</h3><p>{String(item.category??"Aviso RADAR")} · {item.municipality_code?`Municipio ${item.municipality_code}`:"Todos los municipios"}</p><p>{String(item.file_name??item.body).slice(0,150)}</p><div className="client-actions"><button onClick={()=>setPreview(item)}>Revisar</button>{kind==="notice"&&item.status!=="ARCHIVED"&&<button disabled={busy} onClick={()=>void action("archive_content",{id:item.id})}>Retirar</button>}<button disabled={busy} onClick={()=>setDeleting(item)}>Eliminar</button></div></article>)}</div>{!items.length&&<div className="client-callout"><h3>{kind==="resource"?"Tu biblioteca empieza aquí":"Sin avisos todavía"}</h3><p>Crea un borrador y revísalo antes de publicarlo.</p></div>}
  {deleting&&<div className="client-backdrop"><section className="client-drawer" role="dialog" aria-modal="true" aria-label={kind==="resource"?"Eliminar recurso":"Eliminar aviso"}><header><h2>{kind==="resource"?"Eliminar recurso":"Eliminar aviso"}</h2><button disabled={busy} onClick={()=>setDeleting(null)}>×</button></header><form className="client-body superadmin-form" onSubmit={async e=>{e.preventDefault();const confirmation=String(new FormData(e.currentTarget).get("confirmation"));if(await action(kind==="resource"?"delete_resource":"delete_notice",{id:deleting.id,confirmation}))setDeleting(null);}}><h3>{String(deleting.title)}</h3><p>{kind==="resource"?"El documento y su archivo se borrarán definitivamente de la biblioteca y de los municipios.":"El aviso y sus confirmaciones de lectura se borrarán definitivamente. Dejará de aparecer en los municipios."}</p><label>Escribí ELIMINAR para confirmar<input name="confirmation" required pattern="ELIMINAR" autoComplete="off"/></label><button className="superadmin-primary" disabled={busy}>Eliminar definitivamente</button><button type="button" disabled={busy} onClick={()=>setDeleting(null)}>Cancelar</button></form></section></div>}
  {(open||preview)&&<div className="client-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving&&!busy){setOpen(false);setPreview(null);}}}><section className="client-drawer" role="dialog" aria-modal="true" aria-label={kind==="resource"?"Documento":"Aviso"}><header><h2>{preview?"Revisar publicación":kind==="resource"?"Subir documento":"Crear aviso"}</h2><button disabled={saving||busy} onClick={()=>{setOpen(false);setPreview(null);}}>×</button></header><div className="client-body">{preview?<><h3>{String(preview.title)}</h3><p style={{whiteSpace:"pre-wrap"}}>{String(preview.body)}</p><p>Destino: {String(preview.municipality_code??"Todos los municipios")}</p><p>Desde: {new Date(String(preview.starts_at)).toLocaleString("es-GT")}<br/>Hasta: {preview.ends_at?new Date(String(preview.ends_at)).toLocaleString("es-GT"):"Sin fecha final"}</p>{preview.file_name&&<p>Archivo: {String(preview.file_name)} · versión {String(preview.version)}</p>}{preview.status!=="PUBLISHED"&&<button className="superadmin-primary" disabled={busy} onClick={async()=>{if(await action("publish_content",{id:preview.id}))setPreview(null);}}>Publicar</button>}</>:<form className="superadmin-form" onSubmit={submit}><label>Título<input name="title" required maxLength={150}/></label><label>{kind==="resource"?"Descripción":"Mensaje"}<textarea name="body" required maxLength={4000}/></label>{kind==="resource"&&<><label>Carpeta<select name="category">{["Manuales","Checklists","Plantillas","Tutoriales y Capacitación"].map(c=><option key={c}>{c}</option>)}</select></label><label>Versión<input name="version" defaultValue="1" required/></label><label>Archivo · máximo 25 MB<input name="file" type="file" accept={resourceAccept} required/><small>Word, Excel, PowerPoint, PDF, CSV, TXT, imágenes y MP4. Para vista previa de Office usa DOCX, XLSX o PPTX; los formatos antiguos quedan disponibles para descargar.</small></label></>}
   <label>Destinatarios<select name="municipality_code"><option value="">Todos los municipios</option>{snapshot.municipalities.map(m=><option key={m.municipality_code} value={m.municipality_code}>{m.municipality_name} · {m.department_name}</option>)}</select></label><label>Inicio de publicación<input type="datetime-local" name="starts_at"/></label><label>Fin de publicación<input type="datetime-local" name="ends_at" required={kind==="notice"}/></label><p>Se guardará como borrador. Podrás revisar el contenido y los destinatarios antes de publicarlo.</p>{error&&<p role="alert">{error}</p>}<button className="superadmin-primary" disabled={saving||busy}>{saving?"Guardando…":"Guardar borrador"}</button></form>}</div></section></div>}
 </>;
}
export function DemoWorkspace({snapshot,action,busy}:Omit<Props,"refresh">){
 const [selected,setSelected]=useState<Row|null>(null);
 const [batch,setBatch]=useState<Row[]|null>(null);
 const [running,setRunning]=useState(false);
 const [completed,setCompleted]=useState(0);
 const [batchMessage,setBatchMessage]=useState("");
 const batchLock=useRef(false);
 const locked=busy||running;
 async function resetAll(event:FormEvent<HTMLFormElement>){
  event.preventDefault();
  if(batchLock.current||!batch?.length||new FormData(event.currentTarget).get("confirmation")!=="REINICIAR DEMOS")return;
  batchLock.current=true;setRunning(true);setBatchMessage("");
  const targets=[...batch];let done=0;
  try{
   for(const demo of targets){
    if(demo.is_demo!==true)throw new Error("El lote contiene una campaña que no es demo.");
    if(!await action("reset_demo",{campaign_id:demo.id,confirmation:demo.name})){
     setBatchMessage(`Proceso detenido en ${String(demo.name)}. ${done} demos reiniciadas; ${targets.length-done} pendientes. Podés reintentar después de resolver el aviso.`);return;
    }
    done++;setCompleted(done);setBatch(targets.slice(done));
   }
   setBatchMessage(`${done} demos reiniciadas. Todas las seleccionadas quedaron sin cambios.`);
  }catch(error){setBatchMessage(error instanceof Error?error.message:"No se pudo completar el reinicio.");}
  finally{batchLock.current=false;setRunning(false);}
 }
 const [filter,setFilter]=useState("changed");
 const [query,setQuery]=useState("");
 useDismissibleDialog(Boolean(selected||batch),()=>{setSelected(null);setBatch(null);},locked);
 const demos=snapshot.campaigns.filter(c=>c.is_demo===true&&c.status!=="archived");
 const changed=demos.filter(c=>c.demo_has_changes===true);
 const visible=demos.filter(c=>(filter!=="changed"||c.demo_has_changes===true)&&`${c.name} ${c.municipality_code??""}`.toLocaleLowerCase("es-GT").includes(query.toLocaleLowerCase("es-GT"))).sort((a,b)=>Number(b.demo_has_changes===true)-Number(a.demo_has_changes===true)||String(b.demo_last_changed_at??"").localeCompare(String(a.demo_last_changed_at??""))||String(a.municipality_code??"").localeCompare(String(b.municipality_code??"")));
 return <><p>Una demo se marca cuando se guardan cambios. Navegar o consultar información no cambia su estado.</p>
 <div className="demo-controls"><div className="demo-segments" role="group" aria-label="Filtrar demostraciones"><button type="button" aria-pressed={filter==="changed"} onClick={()=>setFilter("changed")}><span>Con cambios</span><b>{changed.length}</b></button><button type="button" aria-pressed={filter==="all"} onClick={()=>setFilter("all")}><span>Todos los municipios</span><b>{demos.length}</b></button></div><label className="demo-search"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 4.5 4.5"/></svg><input aria-label="Buscar municipio por nombre o código" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar municipio o código…"/></label><button className="demo-reset-all" type="button" disabled={locked||!changed.length} onClick={()=>{setBatch([...changed]);setCompleted(0);setBatchMessage("");}}>↻ Reiniciar todos ({changed.length})</button></div>
 {batch&&<div className="client-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!locked)setBatch(null);}}><section className="client-drawer" role="dialog" aria-modal="true" aria-labelledby="reset-all-title"><header><h2 id="reset-all-title">Reiniciar todas las demos</h2><button disabled={locked} aria-label="Cerrar" onClick={()=>setBatch(null)}>×</button></header><form className="client-body superadmin-form" onSubmit={resetAll}><p>Se reiniciarán las <strong>{batch.length} demos pendientes</strong> de todos los municipios, independientemente de la búsqueda actual. Se eliminarán sus cambios privados; se conservarán la información oficial y las campañas reales.</p><p>Las demos que ya están sin cambios no necesitan reiniciarse. Mantené esta pantalla abierta hasta terminar.</p><div role="status" aria-live="polite">{running?`Reiniciando demos · ${completed} completadas…`:batchMessage}</div>{batch.length>0&&<><label>Escribí REINICIAR DEMOS para confirmar<input name="confirmation" required pattern="REINICIAR DEMOS" autoComplete="off" disabled={locked}/></label><button className="superadmin-primary" disabled={locked}>{running?"Reiniciando…":"Confirmar reinicio de todas"}</button></>}<button type="button" disabled={locked} onClick={()=>setBatch(null)}>{batch.length?"Cancelar":"Listo"}</button></form></section></div>}
 {!visible.length&&<div className="client-callout"><h3>{query?"Sin coincidencias":filter==="changed"?"Todo listo para demostrar":"No hay demostraciones disponibles"}</h3><p>{query?"Prueba con otro nombre o código.":"Las demos sin cambios están en el listado de Todas."}</p></div>}
 <div className="client-grid">{visible.map(c=><article className="client-card" key={String(c.id)}><span className="client-pill">{c.demo_has_changes===true?"Con cambios · pendiente de reiniciar":"Sin cambios"}</span><h3>{String(c.name)}</h3><p>{String(c.municipality_code??"Demostración interna")}</p>{typeof c.demo_last_changed_at==="string"&&<p>Último cambio: {new Date(c.demo_last_changed_at).toLocaleString("es-GT",{timeZone:"America/Guatemala",dateStyle:"medium",timeStyle:"short"})}</p>}<button disabled={locked||c.demo_has_changes!==true} onClick={()=>setSelected(c)}>Reiniciar datos privados</button></article>)}</div>{selected&&<div className="client-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!locked)setSelected(null);}}><section className="client-drawer" role="dialog" aria-modal="true" aria-label="Reiniciar demo"><header><h2>Reiniciar demostración</h2><button disabled={locked} onClick={()=>setSelected(null)}>×</button></header><form className="client-body superadmin-form" onSubmit={async e=>{e.preventDefault();if(await action("reset_demo",{campaign_id:selected.id,...Object.fromEntries(new FormData(e.currentTarget))}))setSelected(null);}}><p>Se eliminarán los cambios privados de esta demo y volverá a «Sin cambios». La información oficial y las campañas reales se conservan.</p><label>Escribe {String(selected.name)}<input name="confirmation" required/></label><button className="superadmin-primary" disabled={locked}>Confirmar reinicio</button></form></section></div>}</>;}
