import {useEffect,useState} from 'react';
import {runAdminAction,type AdminSnapshot} from './radarAdminApi';
type Rollup={generated_at:string;summary:Record<string,number|string|null>;results:Array<{territory:string;party_id:string;party_name:string;candidate_name:string|null;votes:number}>;territories:Array<{territory:string;actas:number;valid_votes:number;blank_votes:number;null_votes:number}>;municipalities:Array<{municipality_code:string;municipality_name:string;fiscales:number;received:number;counted:number;valid_votes:number}>};
const elections=[['ALCALDIA','Alcaldías'],['DIP_DIST','Diputados distritales'],['DIP_NAC','Lista nacional'],['PRESIDENTE','Presidencia']];
const n=(value:unknown)=>Number(value??0).toLocaleString('es-GT');
export function NationalRtd({snapshot}:{snapshot:AdminSnapshot}){
 const [election,setElection]=useState('ALCALDIA'),[year,setYear]=useState(2027),[round,setRound]=useState(1),[department,setDepartment]=useState(''),[municipality,setMunicipality]=useState(''),[territory,setTerritory]=useState(''),[auto,setAuto]=useState(true),[revision,setRevision]=useState(0);
 const [data,setData]=useState<Rollup|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let cancelled=false;let timer:ReturnType<typeof setTimeout>|undefined;setData(null);setError('');
  async function load(){if(cancelled)return;if(document.hidden){timer=setTimeout(load,30000);return;}setBusy(true);try{const next=await runAdminAction<Rollup>('national_rtd',{election_type:election,election_cycle:year,election_round:round,department_code:department,municipality_code:municipality});if(!cancelled){setData(next);setError('');}}catch(e){if(!cancelled)setError(e instanceof Error?e.message:'No se pudo actualizar RTD.');}finally{if(!cancelled){setBusy(false);if(auto)timer=setTimeout(load,30000);}}}
  if(year>=2023&&year<=2100)void load();return()=>{cancelled=true;if(timer)clearTimeout(timer);};
 },[election,year,round,department,municipality,auto,revision]);
 const departments=Array.from(new Map(snapshot.municipalities.map(m=>[m.department_code,m.department_name])).entries()).sort((a,b)=>a[1].localeCompare(b[1]));
 const selected=territory||(data?.territories.length===1?data.territories[0].territory:'');
 const results=(data?.results??[]).filter(r=>r.territory===selected).sort((a,b)=>b.votes-a.votes);
 const total=data?.territories.find(t=>t.territory===selected)?.valid_votes??0;
 const territoryLabel=(code:string)=>election==='ALCALDIA'?(snapshot.municipalities.find(m=>m.municipality_code===code)?.municipality_name??code):election==='DIP_DIST'?`Distrito ${code}`:'Consolidado de territorios seleccionados';
 const changeElection=(value:string)=>{setElection(value);setRound(1);setTerritory('');};
 return <section className="rtd-national">
  <div className="rtd-national-heading"><div><small>DÍA D · CONSOLIDADO NACIONAL</small><h2>Una vista de toda la operación</h2><p>Fiscales, actas y votos de las campañas activas. Resultados preliminares, no oficiales.</p></div><span className="rtd-quality">Consolidado nacional</span></div>
  <div className="rtd-election-tabs" role="group" aria-label="Elección">{elections.map(([id,label])=><button key={id} type="button" aria-pressed={election===id} onClick={()=>changeElection(id)}>{label}</button>)}</div>
  <div className="rtd-national-filters"><label>Año electoral<input type="number" min="2023" max="2100" value={year} onChange={e=>setYear(Number(e.target.value))}/></label>{election==='PRESIDENTE'&&<label>Vuelta<select value={round} onChange={e=>setRound(Number(e.target.value))}><option value="1">Primera vuelta</option><option value="2">Segunda vuelta</option></select></label>}<label>Departamento<select value={department} onChange={e=>{setDepartment(e.target.value);setMunicipality('');setTerritory('');}}><option value="">Todos</option>{departments.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Municipio<select value={municipality} onChange={e=>{setMunicipality(e.target.value);setTerritory('');}}><option value="">Todos</option>{snapshot.municipalities.filter(m=>!department||m.department_code===department).map(m=><option key={m.municipality_code} value={m.municipality_code}>{m.municipality_name} · {m.municipality_code}</option>)}</select></label></div>
  <div className="rtd-update-row"><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/>Actualizar cada 30 segundos</label><span>{data?`Último corte: ${new Date(data.generated_at).toLocaleTimeString('es-GT')}`:'Esperando primer corte'}</span><button type="button" disabled={busy} onClick={()=>setRevision(r=>r+1)}>{busy?'Actualizando…':'Actualizar ahora'}</button></div>
  {error&&<p className="rtd-error" role="alert">{error} {data?'Se conserva el último corte; no está actualizado.':''}</p>}
  {data?<><div className="rtd-national-metrics">{[['Fiscales registrados',data.summary.fiscales],['Municipios con actas válidas',`${n(data.summary.reporting_municipalities)} / ${n(data.summary.municipalities)}`],['Actas contabilizadas',data.summary.counted],['Votos válidos',data.summary.valid_votes]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{typeof value==='number'?n(value):value}</strong></div>)}</div>
  <div className="rtd-reception"><span>Recibidas <b>{n(data.summary.received)}</b></span><span>Pendientes de revisión <b>{n(data.summary.pending)}</b></span><span>Conflictos entre reportes <b>{n(data.summary.conflicts)}</b></span><span>Duplicados excluidos <b>{n(data.summary.duplicates)}</b></span><span>Blancos <b>{n(data.summary.blank_votes)}</b></span><span>Nulos <b>{n(data.summary.null_votes)}</b></span></div>
  {Number(data.summary.missing_context)>0&&<p className="rtd-error">{n(data.summary.missing_context)} registros no tienen año o vuelta identificados y no se suman a este corte.</p>}
  <div className="rtd-results-panel"><div className="rtd-panel-heading"><h3>Resultados por opción electoral</h3>{data.territories.length>1&&<label>Territorio<select value={selected} onChange={e=>setTerritory(e.target.value)}><option value="">Seleccionar territorio</option>{data.territories.map(t=><option key={t.territory} value={t.territory}>{territoryLabel(t.territory)}</option>)}</select></label>}</div>
   {!data.territories.length?<div className="rtd-empty"><h3>Todavía no hay actas listas para sumar</h3><p>Este panel consulta la base real. Las actas se sumarán cuando el flujo fiscal entregue registros confirmados con año, vuelta y territorio verificados.</p></div>:!selected?<p className="rtd-empty">Seleccioná un municipio o distrito para ver sus candidatos y votos. Cada elección territorial conserva su propio resultado.</p>:<><p className="rtd-scope-label">{territoryLabel(selected)} · {n(total)} votos válidos</p><div className="rtd-vote-bars">{results.map(r=><div key={r.party_id}><div><span><b>{r.party_name}</b>{r.candidate_name&&<small>{r.candidate_name}</small>}</span><strong>{n(r.votes)} <small>{total?((r.votes/total)*100).toFixed(1):'0.0'}%</small></strong></div><div className="rtd-bar-track"><i style={{width:`${total?100*r.votes/total:0}%`}}/></div></div>)}</div></>}
  </div>
  <div className="rtd-results-panel"><h3>Recepción por municipio</h3>{data.municipalities.length?<div className="rtd-table-wrap"><table><thead><tr><th>Municipio</th><th>Fiscales</th><th>Recibidas</th><th>Contabilizadas</th><th>Votos válidos</th><th><span className="sr-only">Detalle</span></th></tr></thead><tbody>{data.municipalities.map(m=><tr key={m.municipality_code}><td>{m.municipality_name}<small>{m.municipality_code}</small></td><td>{n(m.fiscales)}</td><td>{n(m.received)}</td><td>{n(m.counted)}</td><td>{n(m.valid_votes)}</td><td><button onClick={()=>{setMunicipality(m.municipality_code);setTerritory('');}}>Ver resultados →</button></td></tr>)}</tbody></table></div>:<p className="rtd-empty">No hay campañas activas para estos filtros.</p>}</div>
  <details className="rtd-method"><summary>Cómo se calcula este corte</summary><p>Se suman actas confirmadas o validadas con año, vuelta, JRV y opciones identificadas. Borradores y reportes incompletos quedan pendientes. Cada acta municipal, por centro y JRV, se cuenta una vez; las copias coincidentes se excluyen y las discrepancias quedan fuera de la suma hasta su revisión. Demos y campañas inactivas no se incluyen.</p><p>Alcaldías se presentan por municipio; diputados distritales, por el distrito indicado en el acta; Presidencia y Lista Nacional admiten consolidación entre municipios. Los porcentajes usan únicamente votos válidos contabilizados y no representan el avance sobre el padrón.</p><p>El acceso a este consolidado es exclusivo de superadministración. La autorización y alcance del tratamiento se incorporarán expresamente al contrato del cliente.</p></details></>:!error&&<p className="rtd-empty" role="status">Consultando el consolidado…</p>}
 </section>;
}
