import { useEffect, useMemo, useState, type FormEvent } from 'react';
import type { AdminSnapshot } from './radarAdminApi';
import { ensureRadarAccessToken } from '../data/radarAuth';
import { AdminReverification } from './AdminReverification';
type Batch={id:string;title:string;starts_at:string;activity_type:string;is_demo:string;result:{created:number;without_candidates:number}};
type Draft={request_id:string;title:string;activity_type:string;starts_at:string;community:string;notes:string;is_demo:boolean;campaign_ids:string[]};
async function request<T>(action:string,input:unknown={}):Promise<T>{
 const token=await ensureRadarAccessToken();const res=await fetch(`${String(import.meta.env.VITE_SUPABASE_URL).replace(/\/$/,'')}/functions/v1/radar-admin-agenda`,{method:'POST',headers:{Authorization:`Bearer ${token}`,apikey:String(import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY),'Content-Type':'application/json'},body:JSON.stringify({action,input})});
 const payload=await res.json();if(!res.ok)throw new Error(payload.error||'No se pudo completar la solicitud.');return payload.data;
}
const types=[['ASAMBLEA','ASAMBLEA'],['REUNION','Reunión'],['VISITA','Visita'],['MITIN','Mitin'],['CAMINATA','Caminata / caravana'],['EVENTO','Evento'],['RECORRIDO','Recorrido'],['CAPACITACION','Capacitación'],['OTRA','Otra']];
export default function SharedActivities({snapshot}:{snapshot:AdminSnapshot}){
 const [demo,setDemo]=useState(false),[all,setAll]=useState(false),[chosen,setChosen]=useState<string[]>([]),[query,setQuery]=useState('');
 const [preview,setPreview]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[reverify,setReverify]=useState(false),[batches,setBatches]=useState<Batch[]>([]),[version,setVersion]=useState(0);
 const campaigns=useMemo(()=>snapshot.campaigns.filter(c=>c.status==='active'&&c.is_demo===demo).sort((a,b)=>String(a.municipality_code).localeCompare(String(b.municipality_code))),[snapshot.campaigns,demo]);
 const label=(c:Record<string,unknown>)=>{const m=snapshot.municipalities.find(m=>m.municipality_code===c.municipality_code);return m?`${m.municipality_name} · ${m.department_name}`:String(c.name);};
 const targets=campaigns.filter(c=>all||chosen.includes(String(c.id)));
 const visible=campaigns.filter(c=>`${label(c)} ${c.name} ${c.municipality_code}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es')));
 async function refresh(){try{setBatches(await request<Batch[]>('list'));}catch(e){handleError(e);}}
 function handleError(e:unknown){const text=e instanceof Error?e.message:'No se pudo completar.';if(text==='MFA_AAL2_REQUIRED'){setReverify(true);setError('Confirma tu identidad. El formulario se conserva.');}else setError(text);}
 useEffect(()=>{void refresh();},[]);
 function review(event:FormEvent<HTMLFormElement>){event.preventDefault();setError('');setMessage('');if(!targets.length){setError('Selecciona al menos un municipio con campaña activa.');return;}const f=new FormData(event.currentTarget);setPreview({request_id:crypto.randomUUID(),title:String(f.get('title')).trim(),activity_type:String(f.get('activity_type')),starts_at:new Date(`${f.get('starts_at')}:00-06:00`).toISOString(),community:String(f.get('community')).trim(),notes:String(f.get('notes')).trim(),is_demo:demo,campaign_ids:targets.map(c=>String(c.id))});}
 async function publish(){if(!preview||busy)return;setBusy(true);setError('');try{const result=await request<{created:number;without_candidates:number}>('create',preview);setMessage(`Actividad creada en ${result.created} campañas. ${result.without_candidates} sin candidatos registrados: sus participantes quedaron vacíos.`);setPreview(null);setChosen([]);setAll(false);setVersion(v=>v+1);await refresh();}catch(e){handleError(e);}finally{setBusy(false);}}
 return <><section className="superadmin-panel shared-agenda"><header><div><span>COORDINACIÓN CENTRAL</span><h2>Una actividad, varias agendas</h2></div><span className="client-pill">{targets.length} municipios seleccionados</span></header>
 <p className="shared-agenda-intro">Publica una actividad en las agendas seleccionadas. Cada campaña recibe una copia con sus candidatos actuales como participantes; si no hay candidatos, los campos quedan vacíos.</p>
 {message&&<p className="superadmin-action-message" role="status">{message}</p>}{error&&<p className="superadmin-action-message is-error" role="alert">{error}</p>}
 {preview?<div className="shared-agenda-review"><span>REVISIÓN ANTES DE PUBLICAR</span><h3>{preview.title}</h3><p>{new Date(preview.starts_at).toLocaleString('es-GT',{timeZone:'America/Guatemala'})} · {preview.activity_type}</p><p>{preview.community||'Lugar pendiente de definir'}</p><p style={{whiteSpace:'pre-wrap'}}>{preview.notes}</p><strong>{preview.campaign_ids.length} campañas {preview.is_demo?'demo':'reales'}</strong><div className="shared-agenda-chips">{campaigns.filter(c=>preview.campaign_ids.includes(String(c.id))).map(c=><span key={String(c.id)}>{label(c)}</span>)}</div><p>Se identificarán como «Creada por el administrador de campaña». No se asignará un responsable automáticamente.</p><footer><button type="button" disabled={busy} onClick={()=>setPreview(null)}>Volver a editar</button><button type="button" className="superadmin-primary" disabled={busy} onClick={()=>void publish()}>{busy?'Publicando…':`Crear en ${preview.campaign_ids.length} agendas`}</button></footer></div>:null}<form hidden={Boolean(preview)} key={version} className="superadmin-form shared-agenda-form" onSubmit={review}>
 <div className="shared-agenda-fields"><label>Título de la actividad<input name="title" required maxLength={180} placeholder="Nombre de la actividad"/></label><label>Tipo<select name="activity_type" defaultValue="ASAMBLEA">{types.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>Fecha y hora · Guatemala<input name="starts_at" type="datetime-local" required/></label><label>Lugar o referencia común<input name="community" maxLength={300} placeholder="Opcional · sede, dirección o enlace"/></label><label className="wide">Descripción y notas<textarea name="notes" rows={3} maxLength={4000} placeholder="Información práctica para los equipos"/></label></div>
 <fieldset className="shared-agenda-targets"><legend>¿Quiénes la recibirán?</legend><div className="shared-agenda-toolbar"><div className="shared-agenda-segments" role="group" aria-label="Entorno">{[false,true].map(v=><button key={String(v)} type="button" aria-pressed={demo===v} onClick={()=>{setDemo(v);setAll(false);setChosen([]);}}>{v?'Demostraciones':'Campañas reales'}</button>)}</div><input type="search" aria-label="Buscar municipios destinatarios" placeholder="Buscar municipio o campaña" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <label className="shared-agenda-all"><input type="checkbox" checked={all} onChange={e=>{setAll(e.target.checked);setChosen([]);}}/><span>Todos los municipios con campaña activa <small>({campaigns.length})</small></span></label>
 <div className="shared-agenda-options">{visible.map(c=><label key={String(c.id)}><input type="checkbox" checked={all||chosen.includes(String(c.id))} disabled={all} onChange={e=>setChosen(ids=>e.target.checked?[...ids,String(c.id)]:ids.filter(id=>id!==c.id))}/><span><b>{label(c)}</b><small>{String(c.name)} · {String(c.municipality_code??'')}</small></span></label>)}{!visible.length&&<p>No hay campañas activas que coincidan.</p>}</div>
 <p>La selección incluye únicamente campañas activas de este entorno. No crea contratos ni asigna actividades a municipios todavía disponibles.</p></fieldset><footer><span>Los equipos podrán completar lugar, responsable y participantes en su Agenda.</span><button className="superadmin-primary" disabled={!targets.length}>Revisar actividad →</button></footer></form>
 </section><section className="superadmin-panel shared-agenda-history"><header><div><span>PUBLICACIONES RECIENTES</span><h2>Actividades creadas desde administración</h2></div></header>{batches.length?batches.map(b=><article key={b.id}><div><b>{b.title}</b><small>{new Date(b.starts_at).toLocaleString('es-GT',{timeZone:'America/Guatemala'})} · {b.is_demo==='true'?'Demo':'Real'}</small></div><span>{b.result.created} agendas</span></article>):<p>Aún no hay actividades publicadas desde esta sección.</p>}</section>
 {reverify&&<AdminReverification onClose={()=>setReverify(false)} onDone={()=>{setReverify(false);setError('');void refresh();}}/>}</>;
}
