-- Día D fiscal access grants. Credentials are generated by an Edge Function and
-- only their SHA-256 digests reach Postgres. The existing campaign assignment is
-- the authority for fiscal, municipality, center and JRV scope.

create table campaign_vault.day_d_access_grants (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  assignment_record_id uuid not null references campaign_vault.campaign_records(id) on delete cascade,
  fiscal_id uuid not null references campaign_vault.contacts(id) on delete restrict,
  fiscal_name text not null,
  municipality_code text not null,
  center_id text not null,
  jrv integer not null,
  campaign_name text not null,
  municipality_name text not null,
  center_name text not null,
  center_reference text not null,
  responsible_name text not null,
  party_name text not null,
  token_hash text not null unique,
  code_hash text not null unique,
  status text not null default 'active',
  expires_at timestamptz not null,
  issued_by uuid not null references auth.users(id) on delete restrict,
  issued_at timestamptz not null default now(),
  last_used_at timestamptz,
  status_changed_at timestamptz,
  regenerated_from uuid references campaign_vault.day_d_access_grants(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint day_d_access_grants_municipality_check check (municipality_code ~ '^[0-9]{4}$'),
  constraint day_d_access_grants_center_check check (length(btrim(center_id)) between 1 and 96),
  constraint day_d_access_grants_jrv_check check (jrv > 0),
  constraint day_d_access_grants_token_hash_check check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint day_d_access_grants_code_hash_check check (code_hash ~ '^[0-9a-f]{64}$'),
  constraint day_d_access_grants_status_check check (status in ('active','suspended','revoked','expired')),
  constraint day_d_access_grants_expiry_check check (expires_at > issued_at)
);

create unique index day_d_access_grants_assignment_current_idx
  on campaign_vault.day_d_access_grants (assignment_record_id)
  where status in ('active','suspended');
create index day_d_access_grants_campaign_status_idx
  on campaign_vault.day_d_access_grants (campaign_id,status,expires_at);
create index day_d_access_grants_scope_idx
  on campaign_vault.day_d_access_grants (campaign_id,municipality_code,center_id,jrv,fiscal_id);

create table campaign_vault.day_d_fiscal_sessions (
  id uuid primary key default gen_random_uuid(),
  grant_id uuid not null references campaign_vault.day_d_access_grants(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'active',
  device_hash text,
  bound_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint day_d_fiscal_sessions_status_check check (status in ('active','revoked','expired')),
  constraint day_d_fiscal_sessions_device_hash_check check (device_hash is null or device_hash ~ '^[0-9a-f]{64}$'),
  constraint day_d_fiscal_sessions_expiry_check check (expires_at > bound_at)
);

create unique index day_d_fiscal_sessions_one_device_idx
  on campaign_vault.day_d_fiscal_sessions (grant_id)
  where status = 'active';
create index day_d_fiscal_sessions_user_status_idx
  on campaign_vault.day_d_fiscal_sessions (auth_user_id,status,expires_at);

create table campaign_vault.day_d_access_attempts (
  id bigint generated always as identity primary key,
  auth_user_id uuid references auth.users(id) on delete set null,
  network_hash text,
  credential_kind text not null,
  outcome text not null,
  attempted_at timestamptz not null default now(),
  constraint day_d_access_attempts_network_hash_check check (network_hash is null or network_hash ~ '^[0-9a-f]{64}$'),
  constraint day_d_access_attempts_kind_check check (credential_kind in ('token','code')),
  constraint day_d_access_attempts_outcome_check check (outcome in ('accepted','invalid','expired','suspended','revoked','rate_limited'))
);

create index day_d_access_attempts_user_time_idx
  on campaign_vault.day_d_access_attempts (auth_user_id,attempted_at desc);
create index day_d_access_attempts_network_time_idx
  on campaign_vault.day_d_access_attempts (network_hash,attempted_at desc)
  where network_hash is not null;

create table campaign_vault.day_d_audit_events (
  id bigint generated always as identity primary key,
  campaign_id uuid references public.campaigns(id) on delete restrict,
  grant_id uuid references campaign_vault.day_d_access_grants(id) on delete restrict,
  session_id uuid references campaign_vault.day_d_fiscal_sessions(id) on delete restrict,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  event_data jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  constraint day_d_audit_events_data_object_check check (jsonb_typeof(event_data) = 'object')
);

create index day_d_audit_events_campaign_time_idx
  on campaign_vault.day_d_audit_events (campaign_id,occurred_at desc,id desc);
create index day_d_audit_events_grant_time_idx
  on campaign_vault.day_d_audit_events (grant_id,occurred_at desc,id desc);

-- Retire the former browser-generated plaintext credential records. They cannot
-- be exchanged by the server-backed portal and must not remain usable or stored.
update campaign_vault.campaign_records
set status='REVOCADO',payload=payload-'code',updated_at=now()
where module_key='dia-d' and category='ACCESO_FISCAL';

alter table campaign_vault.day_d_access_grants enable row level security;
alter table campaign_vault.day_d_fiscal_sessions enable row level security;
alter table campaign_vault.day_d_access_attempts enable row level security;
alter table campaign_vault.day_d_audit_events enable row level security;

revoke all on campaign_vault.day_d_access_grants from public,anon,authenticated;
revoke all on campaign_vault.day_d_fiscal_sessions from public,anon,authenticated;
revoke all on campaign_vault.day_d_access_attempts from public,anon,authenticated;
revoke all on campaign_vault.day_d_audit_events from public,anon,authenticated;
grant usage on schema campaign_vault to service_role;
grant select,insert,update on campaign_vault.day_d_access_grants to authenticated;
grant select on campaign_vault.day_d_fiscal_sessions to authenticated;
grant select on campaign_vault.day_d_audit_events to authenticated;
grant all on campaign_vault.day_d_access_grants to service_role;
grant all on campaign_vault.day_d_fiscal_sessions to service_role;
grant all on campaign_vault.day_d_access_attempts to service_role;
grant all on campaign_vault.day_d_audit_events to service_role;
grant usage,select on sequence campaign_vault.day_d_access_attempts_id_seq to service_role;
grant usage,select on sequence campaign_vault.day_d_audit_events_id_seq to service_role;

create policy day_d_access_grants_admin_select
on campaign_vault.day_d_access_grants for select to authenticated
using (
  coalesce((auth.jwt()->>'is_anonymous')::boolean,false) is false
  and private.is_campaign_member(campaign_id,array['campaign_admin','campaign_editor','campaign_viewer'])
);

create policy day_d_access_grants_fiscal_select
on campaign_vault.day_d_access_grants for select to authenticated
using (
  exists (
    select 1 from campaign_vault.day_d_fiscal_sessions session
    where session.grant_id = day_d_access_grants.id
      and session.auth_user_id = auth.uid()
      and session.status = 'active'
      and session.expires_at > now()
  )
);

create policy day_d_access_grants_admin_insert
on campaign_vault.day_d_access_grants for insert to authenticated
with check (
  coalesce((auth.jwt()->>'is_anonymous')::boolean,false) is false
  and issued_by = auth.uid()
  and private.is_campaign_member(campaign_id,array['campaign_admin','campaign_editor'])
);

create policy day_d_access_grants_admin_update
on campaign_vault.day_d_access_grants for update to authenticated
using (
  coalesce((auth.jwt()->>'is_anonymous')::boolean,false) is false
  and private.is_campaign_member(campaign_id,array['campaign_admin','campaign_editor'])
)
with check (
  coalesce((auth.jwt()->>'is_anonymous')::boolean,false) is false
  and private.is_campaign_member(campaign_id,array['campaign_admin','campaign_editor'])
);

create policy day_d_fiscal_sessions_own_select
on campaign_vault.day_d_fiscal_sessions for select to authenticated
using (auth_user_id = auth.uid());

create policy day_d_audit_events_admin_select
on campaign_vault.day_d_audit_events for select to authenticated
using (
  coalesce((auth.jwt()->>'is_anonymous')::boolean,false) is false
  and campaign_id is not null
  and private.is_campaign_member(campaign_id,array['campaign_admin','campaign_editor','campaign_viewer'])
);

create or replace function public.radar_fiscal_access_grants_v1(p_campaign_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path=pg_catalog,public,private,campaign_vault,pg_temp
as $$
  select case
    when coalesce((auth.jwt()->>'is_anonymous')::boolean,false) is false
      and private.is_campaign_member(p_campaign_id,array['campaign_admin','campaign_editor','campaign_viewer'])
    then coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',grant_record.id,
        'campaign_id',grant_record.campaign_id,
        'assignment_id',grant_record.assignment_record_id,
        'fiscal_id',grant_record.fiscal_id,
        'fiscal_name',grant_record.fiscal_name,
        'municipality_code',grant_record.municipality_code,
        'center_id',grant_record.center_id,
        'jrv',grant_record.jrv,
        'status',case when grant_record.status='active' and grant_record.expires_at<=now() then 'expired' else grant_record.status end,
        'expires_at',grant_record.expires_at,
        'issued_at',grant_record.issued_at,
        'last_used_at',grant_record.last_used_at,
        'status_changed_at',grant_record.status_changed_at
      ) order by grant_record.issued_at desc)
      from campaign_vault.day_d_access_grants grant_record
      where grant_record.campaign_id=p_campaign_id
    ),'[]'::jsonb)
    else null
  end
$$;

create or replace function public.radar_issue_fiscal_access_v1(
  p_campaign_id uuid,
  p_assignment_id uuid,
  p_token_hash text,
  p_code_hash text,
  p_expires_at timestamptz
)
returns jsonb
language plpgsql
volatile
security invoker
set search_path=pg_catalog,public,private,campaign_vault,pg_temp
as $$
declare
  assignment_record campaign_vault.campaign_records;
  fiscal_record campaign_vault.contacts;
  municipality_value text;
  municipality_name_value text;
  campaign_name_value text;
  party_name_value text;
  previous_grant_id uuid;
  saved campaign_vault.day_d_access_grants;
begin
  if auth.uid() is null or coalesce((auth.jwt()->>'is_anonymous')::boolean,false) then
    raise exception 'permanent authenticated user required' using errcode='42501';
  end if;
  if not private.is_campaign_member(p_campaign_id,array['campaign_admin','campaign_editor']) then
    raise exception 'campaign access denied' using errcode='42501';
  end if;
  if p_token_hash !~ '^[0-9a-f]{64}$' or p_code_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid credential digest' using errcode='22023';
  end if;
  if p_expires_at < now()+interval '15 minutes' or p_expires_at > now()+interval '7 days' then
    raise exception 'invalid access expiry' using errcode='22023';
  end if;

  select * into assignment_record
  from campaign_vault.campaign_records
  where id=p_assignment_id and campaign_id=p_campaign_id
    and module_key='dia-d' and category='ASIGNACION_JRV'
  for update;
  if assignment_record.id is null then
    raise exception 'day d assignment not found' using errcode='P0002';
  end if;

  select * into fiscal_record
  from campaign_vault.contacts
  where id=nullif(assignment_record.payload->>'fiscal_id','')::uuid
    and campaign_id=p_campaign_id and active and is_in_crm;
  if fiscal_record.id is null then
    raise exception 'active crm fiscal required' using errcode='22023';
  end if;

  select municipality.municipality_code,municipality.municipality_name,campaign.name,
    coalesce(identity.party_name,'Organización política')
  into municipality_value,municipality_name_value,campaign_name_value,party_name_value
  from public.campaigns campaign
  join public.municipalities municipality on municipality.id=campaign.municipality_id
  left join campaign_vault.campaign_identity identity on identity.campaign_id=campaign.id
  where campaign.id=p_campaign_id;
  if municipality_value is null then
    raise exception 'campaign municipality required' using errcode='22023';
  end if;

  select id into previous_grant_id
  from campaign_vault.day_d_access_grants
  where assignment_record_id=p_assignment_id and status in ('active','suspended')
  for update;

  if previous_grant_id is not null then
    update campaign_vault.day_d_access_grants
    set status='revoked',status_changed_at=now(),updated_at=now()
    where id=previous_grant_id;
    update campaign_vault.day_d_fiscal_sessions
    set status='revoked',revoked_at=now()
    where grant_id=previous_grant_id and status='active';
  end if;

  insert into campaign_vault.day_d_access_grants(
    campaign_id,assignment_record_id,fiscal_id,municipality_code,center_id,jrv,
    campaign_name,municipality_name,center_name,center_reference,responsible_name,party_name,
    fiscal_name,token_hash,code_hash,expires_at,issued_by,regenerated_from
  ) values (
    p_campaign_id,p_assignment_id,fiscal_record.id,municipality_value,
    nullif(btrim(assignment_record.payload->>'center_id'),''),
    nullif(assignment_record.payload->>'jrv','')::integer,
    campaign_name_value,municipality_name_value,
    coalesce(nullif(btrim(assignment_record.payload->>'center_name'),''),'Centro asignado'),
    coalesce(nullif(btrim(assignment_record.payload->>'center_reference'),''),'Catálogo RADAR de referencia'),
    coalesce(nullif(btrim(assignment_record.payload->>'center_responsible_name'),''),'Pendiente de asignar'),
    party_name_value,
    fiscal_record.full_name,p_token_hash,p_code_hash,p_expires_at,auth.uid(),previous_grant_id
  ) returning * into saved;

  insert into campaign_vault.day_d_audit_events(campaign_id,grant_id,actor_user_id,event_type,event_data)
  values(p_campaign_id,saved.id,auth.uid(),case when previous_grant_id is null then 'access_issued' else 'access_regenerated' end,
    jsonb_build_object('assignment_id',p_assignment_id,'expires_at',saved.expires_at,'previous_grant_id',previous_grant_id));

  return jsonb_build_object(
    'id',saved.id,'campaign_id',saved.campaign_id,'assignment_id',saved.assignment_record_id,
    'fiscal_id',saved.fiscal_id,'fiscal_name',saved.fiscal_name,'municipality_code',saved.municipality_code,
    'center_id',saved.center_id,'jrv',saved.jrv,'status',saved.status,
    'expires_at',saved.expires_at,'issued_at',saved.issued_at,'last_used_at',saved.last_used_at
  );
end
$$;

create or replace function public.radar_set_fiscal_access_status_v1(
  p_campaign_id uuid,
  p_grant_id uuid,
  p_status text
)
returns jsonb
language plpgsql
volatile
security invoker
set search_path=pg_catalog,public,private,campaign_vault,pg_temp
as $$
declare saved campaign_vault.day_d_access_grants;
begin
  if auth.uid() is null or coalesce((auth.jwt()->>'is_anonymous')::boolean,false) then
    raise exception 'permanent authenticated user required' using errcode='42501';
  end if;
  if not private.is_campaign_member(p_campaign_id,array['campaign_admin','campaign_editor']) then
    raise exception 'campaign access denied' using errcode='42501';
  end if;
  if p_status not in ('active','suspended','revoked') then
    raise exception 'invalid access status' using errcode='22023';
  end if;
  update campaign_vault.day_d_access_grants
  set status=p_status,status_changed_at=now(),updated_at=now()
  where id=p_grant_id and campaign_id=p_campaign_id
  returning * into saved;
  if saved.id is null then raise exception 'access grant not found' using errcode='P0002'; end if;

  if p_status <> 'active' then
    update campaign_vault.day_d_fiscal_sessions
    set status='revoked',revoked_at=now()
    where grant_id=saved.id and status='active';
  end if;
  insert into campaign_vault.day_d_audit_events(campaign_id,grant_id,actor_user_id,event_type,event_data)
  values(p_campaign_id,saved.id,auth.uid(),'access_'||p_status,jsonb_build_object('status',p_status));
  return jsonb_build_object(
    'id',saved.id,'campaign_id',saved.campaign_id,'assignment_id',saved.assignment_record_id,
    'fiscal_id',saved.fiscal_id,'fiscal_name',saved.fiscal_name,'municipality_code',saved.municipality_code,
    'center_id',saved.center_id,'jrv',saved.jrv,'status',saved.status,
    'expires_at',saved.expires_at,'issued_at',saved.issued_at,'last_used_at',saved.last_used_at,
    'status_changed_at',saved.status_changed_at
  );
end
$$;

create or replace function public.radar_exchange_fiscal_access_v1(
  p_credential_hash text,
  p_credential_kind text,
  p_auth_user_id uuid,
  p_network_hash text default null,
  p_device_hash text default null
)
returns jsonb
language plpgsql
volatile
security invoker
set search_path=pg_catalog,public,private,campaign_vault,pg_temp
as $$
declare
  matched campaign_vault.day_d_access_grants;
  session_record campaign_vault.day_d_fiscal_sessions;
  failed_attempts integer;
  outcome_value text;
begin
  if current_user <> 'service_role' then
    raise exception 'server exchange required' using errcode='42501';
  end if;
  if p_credential_hash !~ '^[0-9a-f]{64}$' or p_credential_kind not in ('token','code') then
    raise exception 'invalid exchange request' using errcode='22023';
  end if;
  if p_network_hash is not null and p_network_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid network digest' using errcode='22023';
  end if;
  if p_device_hash is not null and p_device_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid device digest' using errcode='22023';
  end if;

  select count(*) into failed_attempts
  from campaign_vault.day_d_access_attempts
  where attempted_at > now()-interval '15 minutes'
    and outcome in ('invalid','expired','suspended','revoked','rate_limited')
    and (auth_user_id=p_auth_user_id or (p_network_hash is not null and network_hash=p_network_hash));
  if failed_attempts >= 5 then
    insert into campaign_vault.day_d_access_attempts(auth_user_id,network_hash,credential_kind,outcome)
    values(p_auth_user_id,p_network_hash,p_credential_kind,'rate_limited');
    return jsonb_build_object('ok',false,'reason','rate_limited');
  end if;

  if p_credential_kind='token' then
    select * into matched from campaign_vault.day_d_access_grants where token_hash=p_credential_hash for update;
  else
    select * into matched from campaign_vault.day_d_access_grants where code_hash=p_credential_hash for update;
  end if;
  if matched.id is null then
    insert into campaign_vault.day_d_access_attempts(auth_user_id,network_hash,credential_kind,outcome)
    values(p_auth_user_id,p_network_hash,p_credential_kind,'invalid');
    return jsonb_build_object('ok',false,'reason','invalid');
  end if;

  outcome_value := case
    when matched.expires_at <= now() then 'expired'
    when matched.status='suspended' then 'suspended'
    when matched.status='revoked' then 'revoked'
    when matched.status='expired' then 'expired'
    else 'accepted'
  end;
  insert into campaign_vault.day_d_access_attempts(auth_user_id,network_hash,credential_kind,outcome)
  values(p_auth_user_id,p_network_hash,p_credential_kind,outcome_value);
  if outcome_value <> 'accepted' then
    if outcome_value='expired' and matched.status='active' then
      update campaign_vault.day_d_access_grants set status='expired',status_changed_at=now(),updated_at=now() where id=matched.id;
    end if;
    return jsonb_build_object('ok',false,'reason',outcome_value);
  end if;

  update campaign_vault.day_d_fiscal_sessions
  set status='revoked',revoked_at=now()
  where grant_id=matched.id and status='active';
  insert into campaign_vault.day_d_fiscal_sessions(grant_id,auth_user_id,device_hash,expires_at)
  values(matched.id,p_auth_user_id,p_device_hash,matched.expires_at)
  returning * into session_record;
  update campaign_vault.day_d_access_grants set last_used_at=now(),updated_at=now() where id=matched.id;
  insert into campaign_vault.day_d_audit_events(campaign_id,grant_id,session_id,actor_user_id,event_type,event_data)
  values(matched.campaign_id,matched.id,session_record.id,p_auth_user_id,'access_exchanged',jsonb_build_object('credential_kind',p_credential_kind));

  return jsonb_build_object(
    'ok',true,'session_id',session_record.id,'grant_id',matched.id,
    'assignment_id',matched.assignment_record_id,'auth_user_id',p_auth_user_id,
    'expires_at',session_record.expires_at,
    'campaign_id',matched.campaign_id,'campaign_name',matched.campaign_name,
    'party_name',matched.party_name,'municipality_code',matched.municipality_code,
    'municipality_name',matched.municipality_name,
    'center_id',matched.center_id,'jrv',matched.jrv,'fiscal_id',matched.fiscal_id,
    'fiscal_name',matched.fiscal_name,'center_name',matched.center_name,
    'center_reference',matched.center_reference,'responsible_name',matched.responsible_name
  );
end
$$;

create or replace function public.radar_validate_fiscal_session_v1(
  p_session_id uuid,
  p_grant_id uuid
)
returns jsonb
language plpgsql
volatile
security invoker
set search_path=pg_catalog,public,private,campaign_vault,pg_temp
as $$
declare
  session_record campaign_vault.day_d_fiscal_sessions;
  grant_record campaign_vault.day_d_access_grants;
begin
  if current_user <> 'service_role' then
    raise exception 'server validation required' using errcode='42501';
  end if;
  select * into session_record
  from campaign_vault.day_d_fiscal_sessions
  where id=p_session_id and grant_id=p_grant_id and status='active' and expires_at>now()
  for update;
  if session_record.id is null then return jsonb_build_object('ok',false); end if;
  select * into grant_record
  from campaign_vault.day_d_access_grants
  where id=p_grant_id and status='active' and expires_at>now();
  if grant_record.id is null then return jsonb_build_object('ok',false); end if;
  update campaign_vault.day_d_fiscal_sessions set last_seen_at=now() where id=session_record.id;
  return jsonb_build_object(
    'ok',true,'session_id',session_record.id,'grant_id',grant_record.id,
    'assignment_id',grant_record.assignment_record_id,'auth_user_id',session_record.auth_user_id,
    'expires_at',session_record.expires_at,'campaign_id',grant_record.campaign_id,
    'municipality_code',grant_record.municipality_code,'center_id',grant_record.center_id,
    'jrv',grant_record.jrv,'fiscal_id',grant_record.fiscal_id
  );
end
$$;

create or replace function public.radar_fiscal_session_scope_v1()
returns jsonb
language sql
stable
security invoker
set search_path=pg_catalog,public,private,campaign_vault,pg_temp
as $$
  select coalesce((
    select jsonb_build_object(
      'session_id',session.id,'expires_at',session.expires_at,
      'campaign_id',grant_record.campaign_id,'municipality_code',grant_record.municipality_code,
      'center_id',grant_record.center_id,'jrv',grant_record.jrv,
      'fiscal_id',grant_record.fiscal_id,'fiscal_name',grant_record.fiscal_name
    )
    from campaign_vault.day_d_fiscal_sessions session
    join campaign_vault.day_d_access_grants grant_record on grant_record.id=session.grant_id
    where session.auth_user_id=auth.uid() and session.status='active'
      and session.expires_at>now() and grant_record.status='active' and grant_record.expires_at>now()
    order by session.bound_at desc limit 1
  ),'{}'::jsonb)
$$;

revoke all on function public.radar_fiscal_access_grants_v1(uuid) from public,anon;
revoke all on function public.radar_issue_fiscal_access_v1(uuid,uuid,text,text,timestamptz) from public,anon;
revoke all on function public.radar_set_fiscal_access_status_v1(uuid,uuid,text) from public,anon;
revoke all on function public.radar_exchange_fiscal_access_v1(text,text,uuid,text,text) from public,anon,authenticated;
revoke all on function public.radar_validate_fiscal_session_v1(uuid,uuid) from public,anon,authenticated;
revoke all on function public.radar_fiscal_session_scope_v1() from public,anon;
grant execute on function public.radar_fiscal_access_grants_v1(uuid) to authenticated;
grant execute on function public.radar_issue_fiscal_access_v1(uuid,uuid,text,text,timestamptz) to authenticated;
grant execute on function public.radar_set_fiscal_access_status_v1(uuid,uuid,text) to authenticated;
grant execute on function public.radar_exchange_fiscal_access_v1(text,text,uuid,text,text) to service_role;
grant execute on function public.radar_validate_fiscal_session_v1(uuid,uuid) to service_role;
grant execute on function public.radar_fiscal_session_scope_v1() to authenticated;

-- Audit rows are append-only. Even service-side code receives no UPDATE/DELETE grant.
revoke update,delete,truncate on campaign_vault.day_d_audit_events from public,anon,authenticated,service_role;
