import React from 'react';
import {createRoot} from 'react-dom/client';
import {MemoryRouter} from 'react-router-dom';
import {ContentWorkspace} from './src/admin/ContentWorkspace';
import ResourceRecordSheet from './src/components/ResourceRecordSheet';
import {MunicipalityProvider} from './src/context/MunicipalityContext';
import './src/styles/global.css';
import './src/styles/v70/fonts.css';
import './src/styles/v70/globals.css';
import './src/styles/v70/portal.css';
import './src/styles/v70/radar-brand-v3.css';
import './src/styles/canonical-adapter.css';
import './src/styles/superadmin.css';
const params=new URLSearchParams(location.search);
const municipalities=[{municipality_code:'0501',municipality_name:'Escuintla',department_name:'Escuintla'},{municipality_code:'0509',municipality_name:'San José',department_name:'Escuintla'}];
const snapshot={municipalities,shared_content:[],campaigns:[]};
window.__submitted=[];
const props={snapshot,busy:false,refresh:async()=>{},action:async(name,input)=>{window.__submitted.push({name,input});return true}};
const consumer={municipality:{code:'0501',name:'Escuintla',department:'Escuintla'},context:{is_demo:params.has('demo'),campaign_id:'',permissions:[]}};
createRoot(document.getElementById('root')!).render(params.has('sheet')?<MunicipalityProvider consumer={consumer as any}><ResourceRecordSheet record={{id:'qa',title:'Camioneta',category:'Vehículo',payload:{responsible:'Equipo de campaña',brand:'Toyota',color:'Blanco',plate:'P-000TEST'}} as any} onClose={()=>{}}/></MunicipalityProvider>:<MemoryRouter><div className="superadmin-shell"><main className="superadmin-workspace" style={{margin:0,padding:40}}><ContentWorkspace {...props as any} kind={params.has('resource')?'resource':'notice'}/></main></div></MemoryRouter>);
